### ISSUE TITLE
Possible improvement on UI: table selection, checkboxes, radiobuttons

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#101]
@chfleming @jmcalabrese @NoonanM 

Recently I learned about some new tricks in UI, and some could be applied to ctmmweb. 

- table selection. The individual summary table actually runs in two mode: 1. no selection means current page is selected 2. with row selection, selected row are selected. This is not always obvious and intuitive. 
  We could make it to be single mode: always use selected rows, and by default select all rows in current page. To make it more obvious that highlighted rows are selected, we can add some icons to selected rows (this need quite some tricks to implement)
<img width="894" alt="Screen Shot 2019-08-25 at 7 00 57 PM" src="https://user-images.githubusercontent.com/25039897/63657074-be057400-c76a-11e9-86a6-40c93435d515.png">

- different appearance of radiobuttons, checkboxes and buttons etc. There is this new package [shinywidgets](http://shinyapps.dreamrs.fr/shinyWidgets/) which provided some alternative looks on radiobuttons and checkboxes. I always felt the default options sometimes are not good looking enough or too boring.

Do you guys feel these worth to be implemented?

**Comment by chfleming** [comment]
I like the table selection default idea and example, except that the "Selected" column is very wide.

**Comment by xhdong-umd** [comment]
Thinking again later for the implementation details, I found the proposed method have its own limitations.

The current method need some learning to know how it works, but once known it's clear and easy to use. If we use the "always select rows explicitly" concept, when we have multiple pages and are proceeding to next page:
- Previously if no row selected, go to next page change current subset to next page; if some rows selected, go to next page just let you view the page but still keep the selection.
- Now if we alway select rows explicitly, there is no real difference between "auto selected all for current page" and "some are selected for current page" logically. When go to next page we probably cannot switch current subset to next page automatically, and user need to go back to previous page, deselect all, go to next page and manual select them.

This seemed to be going backwards in user experience. And there are many users already familiar with current usage, maybe we should still stick to it.

For the other minor widget changes in appearance, that's simple and I'll apply them when found suitable.
