### ISSUE TITLE
Select subset for overlap 

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#103]
This was mentioned by @NoonanM  in #36, moved out as independent issue as the original issue is mostly about overlap feature implementation and is quite long already.

>On the overlap page, it is not currently possible to subset individuals. It would be useful to have the option to select what individuals overlap is calculated for.

>But if a user has done model fitting on all individuals, and then wants to only look at overlap on a subset, they would need to re-run all of their analyses. The main use here is so that users can have plots of overlap values that reflect the individuals they are interested in.

>Yes, the use case would be only for individuals that have model results. Maybe some type of drop down menu, or clickable list of individuals with all selected by default?

**Comment by xhdong-umd** [comment]
The overlap page will calculate all combinations by default automatically. Unless this is taking too much time, I think it's easier to just have an option to limit what individuals will be included in reported result. I can think to add some control let user to filter a subset.

Otherwise if we decided to choose all combination or a subset before the calculation, that need a confirmation dialog or some button to start calculation and change the default behavior totally. I'd rather not to do this unless it's really needed.

**Comment by xhdong-umd** [comment]
@NoonanM, implementing a selector like this should not be too hard
![image](https://user-images.githubusercontent.com/25039897/69684437-abab1700-1086-11ea-9a31-5d1e807f4fa2.png)

However, reading the question again, I think user could just deselect the models/individuals in the model summary page, then all the home range/occurrence/overlap will only based on selected subset. Since this operation apply to all later pages, I would prefer to use this instead an ad hoc filter in overlap page (otherwise what if user want to limit selection in home range?)

**Comment by NoonanM** [comment]
That makes sense. I don't know what the help tab on the overlap page currently says, but if that's the option that works best for estimating subsets of overlaps, I think it would be good to add a mention of that sp that users can know how to do that option.

**Comment by xhdong-umd** [comment]
I do mentioned this in the help:

Model selection help:
- **Selected models in table will be basis of all latter analyses**. 

Overlap help:
### Overlap of Home Ranges
- Home range [Overlap](https://ctmm-initiative.github.io/ctmm/reference/overlap.html) are calculated based on selected models in `Model Selection` page.

I'll add some text to make it more clear.
