### ISSUE TITLE
invalid symbol parameter after UERE; Warning: Error in utils::getS3method: S3 method 'summary.character' not found

### ISSUE THREAD

**Issue by frdmnn** [ctmm-initiative/ctmmweb#104]
Started working on a dataset again that I had no issues with and now whenever I try to either calibrate with own data, or just apply a UERE value, the app shows "invalid symbol parameter". When trying to process with uncalibrated data, I get an error later that summary character was not found. 
I have had no problems with the same calibration and datafile before in the app. 
I just tried to run it in R and get no issues (however want to keep using the webapp preferable for upcoming work).
Initially I thought it might be a timestamp error or something, but I also tried importing the data directly from movebank and experience the same problems. 
Any quick advice would be greatly appreciated, I am in the final stages of my phd data analyses. Thanks in advance!

I'll post info from the R console below:

**Calibration error:** 
 Warning: Error in graphics::symbols: invalid symbol parameter
  172: graphics::symbols
  171: utils::getS3method("plot", CLASS)
  170: plot.list
  168: renderPlot [C:/R-library/ctmmweb/app/server.R#1087]
  166: func
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$error_plot
    2: shiny::runApp
    1: app
[2019-10-25 19:03:24] saving plot as 
	plot_5_histogram_2019-10-25_19-03-24.png 
Saving 14.4 x 3.89 in image
   user  system elapsed 
   1.32    0.24    1.61 

**without calibration when trying to process data:**
 [2019-10-25 17:51:18] Movebank data imported 
	576876709 
[2019-10-25 17:51:18] ## Visualization  
[2019-10-25 17:51:18] Current selected individuals 
	   identity            start              end interval (minutes) duration (days) points calibrated
	1:      CHO 2017-07-26 11:11 2017-07-29 09:39               3.02            2.94    596         no
	2:      DOT 2017-07-22 12:00 2017-07-26 08:05               3.02            3.84    768         no
	3:      FRA 2017-02-20 11:42 2017-02-27 19:55               3.00            7.34    732         no
	4:      GEG 2017-02-25 13:24 2017-02-28 15:15               3.00            3.08    621         no
	5: LOC_1min 2016-09-08 13:30 2016-09-10 09:05               1.00            1.82    796         no
	6: LOC_3min 2016-09-08 13:30 2016-09-10 09:04               3.00            1.82    281         no 
[2019-10-25 17:51:19] saving plot as 
	plot_5_histogram_2019-10-25_17-51-19.png 
Saving 14.4 x 3.89 in image
   user  system elapsed 
   3.28    0.17    3.62 
[2019-10-25 17:51:35] Current selected individuals 
	   identity            start              end interval (minutes) duration (days) points calibrated
	1:      GEG 2017-02-25 13:24 2017-02-28 15:15                  3            3.08    621         no 
[2019-10-25 17:51:36] saving plot as 
	plot_5_histogram_2019-10-25_17-51-36.png 
Saving 14.4 x 3.89 in image
   user  system elapsed 
   1.00    0.15    1.18 
[2019-10-25 17:51:44] ## Model Selection  
[2019-10-25 17:51:45] saving plot as 
	vario_2019-10-25_17-51-45.png 
[2019-10-25 17:51:48] saving plot as 
	vario_2019-10-25_17-51-48.png 
[2019-10-25 17:51:52] Trying different models...  
trying models on single animal with all but one cores
* Fitting model OUF isotropic error.
* Fitting models OUF anisotropic error.
* Fitting models OU anisotropic error, OUf anisotropic error.
   user  system elapsed 
1078.70    2.41 1142.98 
Warning: Error in utils::getS3method: S3 method 'summary.character' not found
  141: [.data.table
  139: ctmmweb:::compare_models
  138: <reactive:try_models> [C:/R-library/ctmmweb/app/server.R#2117]
  122: try_models
  121: <reactive:summary_models> [C:/R-library/ctmmweb/app/server.R#2130]
  105: summary_models
  103: exprFunc [C:/R-library/ctmmweb/app/server.R#2197]
  102: widgetFunc
  101: func
   88: origRenderFunc
   87: renderFunc
   83: origRenderFunc
   82: output$tried_models_summary
    2: shiny::runApp
    1: app

Thanks a lot in advance!!

**Comment by xhdong-umd** [comment]
Is it possible for you to send a small sample data to me so I can reproduce the problem?
