### ISSUE TITLE
Location Data is turned 90° counterclockwise in the Menu -> "Visualization" tab, but not "Map" tab

### ISSUE THREAD

**Issue by MatthiasKlappproth** [ctmm-initiative/ctmmweb#106]
I'm using a dataset downloaded from movebank.org (.csv file). When plotting the attribute table in GQIS/ ArcGIS / rhr / t-locoh / move (decimal degrees as well as UTM), everything is normal and looks identical to the ctmmweb "Map" plot when using the HERE.satelliteDay background (see an example for 1 individual in Fig. 1). Hence, there seems to be no problem with the location data in general.
![Fig1](https://user-images.githubusercontent.com/58523629/70221033-d4e33b80-1747-11ea-9c3e-843fc16248bd.jpg)
When looking at the plot created in the  "Visualization" tab, the data looks like this (Fig.2): 
![Fig 2](https://user-images.githubusercontent.com/58523629/70221273-58049180-1748-11ea-88dd-69ac3981b2cb.jpg).
Consequently, home ranges have the same issue, also when exported into shapefile format for further individual plotting (Fig.3): 
![Fig 3](https://user-images.githubusercontent.com/58523629/70221985-8f277280-1749-11ea-8b21-9a62c921cba0.jpg).

Any idea why the data is turned 90° counterclockwise? I encountered this problem before in the ctmm package as well when using movebank data. Is there any solution to circumvent this?

A further issue I noticed is when plotting the location data in the "Map" tab with the HERE.terrainDay background. Then the data is shifted to the east by a few 100 meters (Fig.4): 
![Fig4](https://user-images.githubusercontent.com/58523629/70222470-694e9d80-174a-11ea-91c6-c10d336ce2c4.jpg)

**Comment by xhdong-umd** [comment]
When ctmm imported telemetry data, it will convert lon/lat to x/y and center them for easier numerical optimization. They may also get rotated to landscape shape(I am not sure the reason, maybe making plots easier to arrange?).

When making map or any other plots that need the actual location, lon/lat were used. 

As for terrain map layer differences, that looks to be the accuracy problem of the map source (the projection should right as the other layer is good) and we have nothing can do about it.

**Comment by MatthiasKlappproth** [comment]
Thanks a lot for the quick reply!
So the rotation issue is a question/ issue for the ctmm-initiative/ctmm and not for the ctmm-initiative/ctmmweb!? Please let me know if I should close the thread and re-open it under ctmm. I assume there is a work-around and @chfleming would be the responsible contact for this?

_As for terrain map layer differences, that looks to be the accuracy problem of the map source (the projection should right as the other layer is good) and we have nothing can do about it._
Nevermind, don't worry! Just something I noticed in addition. The satellite map is preferable anyway...

**Comment by xhdong-umd** [comment]
Yes rotation is done in ctmm end with a purpose, not a bug. It will be better to ask @chfleming if there could a work around, but discussing it here is totally fine with me.

**Comment by chfleming** [comment]
There are two issues here:

In `ctmm` if you do not argument a PROJ4 projection on import then the default one is a 2-point azimuthal, which is a safe projection for distortion, but does not preserve North=up. If you want, you can raise a feature request for `ctmmweb` to be able to accept PROJ4 projection arguments.

As for the second issue with the map being off. I have had users find that QGIS does not render 2-point azimuthal projection correctly, and are off like this. I am curious if this issue also goes away with a simpler projection like 1-point azimuthal.

**Comment by chfleming** [comment]
I should add another thing that I've seen that can cause a shift in the projected data is if the input long-lat and output projection have different datums. I have been using `rgdal::project()`, which assumes datums are consistent, but am about to switch to `sp::spTransform()` to avoid this issue, though the user will have to supply the input datum to get the correct results.
