### ISSUE TITLE
Alternative information criteria in model selection

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#107]
Occasionally, such as with small samples, there is need to use an information criterion (IC) other than the default approximate AICc. It would be useful to have a dropdown box somewhere before model selection to choose an IC other than approximate AICc. This argument would then be fed into the `IC` argument of `ctmm.select` and its model list `summary`. Current ICs supported are `"AICc"`, `"AIC"`, `"BIC"`, `"LOOCV"`, and `"HSCV"`.

**Comment by SandraCuadros123** [comment]
Hi Christen. Thanks, this would be very useful. I had an issue with some of my data because pf the small sample sizes probably and this would really help to solve the problem.

**Comment by xhdong-umd** [comment]
When you used a different IC, summary over multiple attempts models still says AICc? Should that be updated to the actual IC used?

If this is the case, this could be a little bit difficult as the model summary code rely on the column name, and I need to make it work for all possible values...

```r
res_1 <- ctmm.select(tele_list[[1]], tele_guess_list[[1]][[2]], IC = "BIC", verbose = TRUE)
> summary(res_1)
                     ΔAICc ΔRMSPE (m) DOF[area]
OU anisotropic    0.000000  575.84409  26.43320
OUF anisotropic   2.226091  567.44310  26.68302
OUf anisotropic  13.275649   22.30848  50.22548
OU isotropic     24.572981  282.07571  29.28846
OUF isotropic    26.515583  261.64516  30.58978
IID anisotropic 150.133919    0.00000  99.00000
```

**Comment by chfleming** [comment]
You have to provide the `IC` argument to both `ctmm.select` and `summary`. Then it should change.

**Comment by xhdong-umd** [comment]
Got it. Though this means all my model summary code need to be able to handle all possible IC column names, that will not be easy. I'll check how it can be done.

**Comment by xhdong-umd** [comment]
@chfleming , I' implementing this and found error with two IC values. I installed most recent ctmm from github.

```r
library(ctmm)
library(ctmmweb)
library(data.table)

data(buffalo)
tele_list <- pick(buffalo, 100)
model_try_res <- par_try_models(tele_list)
```

```r
> summary(model_try_res[[1]], IC = "BIC")
                      ΔBIC ΔRMSPE (m) DOF[area]
OU anisotropic    0.000000  575.84411  26.43320
OUF anisotropic   4.591844  567.44310  26.68302
OUf anisotropic  13.275649   22.30848  50.22548
OU isotropic     19.702955  282.07571  29.28846
OUF isotropic    24.103176  261.64513  30.58978
IID anisotropic 147.721512    0.00000  98.69296
> summary(model_try_res[[1]], IC = "LOOCV")
Error in is.nan(x) : default method not implemented for type 'list'
> summary(model_try_res[[1]], IC = "HSCV")
Error in is.nan(x) : default method not implemented for type 'list'
```

**Comment by xhdong-umd** [comment]
Maybe I need to use the IC in the model selection step too? I'm running one with LOOCV, but it hasn't finish after quite some time...

**Comment by xhdong-umd** [comment]
LOOCV seem to take extra time to run ctmm.select.

**Comment by chfleming** [comment]
ICs that require extra calculation like LOOCV do also require being set in `ctmm.select`. LOOCV is also an O(n^2) algorithm, so it is very slow, but it's only necessary for tiny datasets.

**Comment by chfleming** [comment]
Also, even if the IC is calculated in the fit object, if it wasn't set in `ctmm.select` then you can ensure that the appropriate models were attempted.

**Comment by xhdong-umd** [comment]
IC option is added. This is like adding a knob to a pipe line of machines, a lot of places need to be adjusted, and it has been so long since I worked on this part so it took extra time to pick up all the complex details.
