### ISSUE TITLE
deal with DOF speed of 0

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#113]
When DOF speed is 0, we may need to give some hint or warning in speed page.

@chfleming @NoonanM What's the exact situation that we need to handle? What model type? What value I need to check? What should be told to user?

**Comment by NoonanM** [comment]
I think a global check on DOF speed should be appropriate. That's a lot more reliable than hunting for different modelsparameters/model names. I believe that you could add a warning that says something like: "Warning: Sampling is too coarse to estimate speed or distance travelled (see help page for more information)." Then on the help page you can add some text along these lines: "If the data are too coarsely sampled, relative to the animal’s movement, to be able to fit a correlated velocity model, no statistically significant signature of the animal’s velocity will remain in the location data. This leaves insufficient information for speed or distance estimation, and it will not be possible to estimate speed or distance travelled. ", and a reference to: Noonan, M.J., Fleming, C.H., Akre, T.S. et al. Scale-insensitive estimation of speed and distance traveled from animal tracking data. Mov Ecol 7, 35 (2019). https://doi.org/10.1186/s40462-019-0177-1

**Comment by xhdong-umd** [comment]
So basically if a row in model fitting results table have DOF speed as 0, we can give a pop up warning. Should this warning show up in modeling page, or speed page, or both?

**Comment by NoonanM** [comment]
I think just the speed page. Users already have a lot to think about when they're working on the modelling, so maybe best to keep that page as clean as possible.

**Comment by xhdong-umd** [comment]
Warning added and the help page updated.
