### ISSUE TITLE
Units of speed on filter outliers page

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#117]
Can we change the displayed units of speed on the filter outliers page to use the median time step in the data as the time unit for speed? 

I think that would make the numbers easier to interpret at a glance, as speed outliers are usually single steps where the animal went faster than it normally does. For example, when the time interval in the data is one hour and there is one offending time step that sticks out from the rest, seeing the speed displayed as 240 km/day is harder to interpret than 10 km/hour. At a glance, the former might seem extreme, while the latter, which is more closely tied to what the animal actually did, could look quite plausible.

**Comment by chfleming** [comment]
I disagree with the median time step, because it can be a weird number. But I'm not against something finer than per day.

**Comment by jmcalabrese** [comment]
Median time step was just a suggestion, but it should be something closer to the typical sampling interval in the data. Any other suggestions for that?

**Comment by xhdong-umd** [comment]
Right now we are using median of time difference in data for "interval". I think it's hard to find a better way to get the sampling interval.

**Comment by chfleming** [comment]
I suppose you could run the median time step through the `unit` function but with a non-default `thresh` threshold argument so that something like 59 minutes is rounded up to an hour? Still, I don't know.

**Comment by jmcalabrese** [comment]
@chfleming not sure I understand the problem here? As Xianghui points out, we've used the median before to define the typical time interval in the data. And this is just to make interpretation of potential outliers easier, not for actually doing analyses under the hood. If you don't think the median will work, how would you define a relevant time interval that is "finer than a day"?

**Comment by chfleming** [comment]
My issue is that the units of speed will be weird if they are numbers like 5 meters per 3 minutes rather than 1.7 meters per minute.

**Comment by xhdong-umd** [comment]
Right now the speed is converted with best fit unit to make the number in a range. For speed outlier purposes, we can just use m/s or km/hour as this unit is easiest to relate to and get a sense. The only exception is some very slow movement usage, which could use smaller unit. But I think m/s or km/hour should be good for most higher speed.

**Comment by jmcalabrese** [comment]
@xhdong-umd I think that is a reasonable solution.

@chfleming Your earlier post said the median (not speed) could be a weird number, which didn't sense to me. Now I see what your concern was, but I think Xianghui's suggested workaround is reasonable and will be easier to interpret than km/day.

**Comment by xhdong-umd** [comment]
I'm working on outlie feature and changed speed unit to km/hour in speed outlier tab.
