### ISSUE TITLE
Add a Start page to the sidebar

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#118]
With the addition of the analysis guide feature, the top two boxes on the "Import" page now have nothing to do with data import. I'm wondering if we should add a "Start" page before "Import" that contains these two boxes, and provides room for any other app config/settings or user guidance/help features we may add in the future?

**Comment by chfleming** [comment]
Or we could change the name of the "Import" page to "Start"?

**Comment by xhdong-umd** [comment]
I think change page name is simpler as we don't have enough content for a complete new page. In the future if we need it we can extract them.

**Comment by xhdong-umd** [comment]
First page renamed to "Start".

**Comment by jmcalabrese** [comment]
I'm fine with this as a short term measure, but think that there should be separate start and import pages longer term. One addition to a pure start page that I could see happening in the near future is a box that contains direct links to ctmmweb (and possibly also ctmm) vignettes.

**Comment by xhdong-umd** [comment]
We can put links in help button window without taking more space, though that is not directly visible.

**Comment by jmcalabrese** [comment]
If vignettes are buried in the help system, lots of users won't find them. The point of the start page idea is to make user aides and config stuff more visible, without muddling the core content of the import page.

Beyond adding an entry in the sidebar, is there any actual cost to adding a separate start page?

**Comment by xhdong-umd** [comment]
There is no cost and it's easy to adjust. Just I'm not sure if the first page will be too sparse with less contents.

**Comment by xhdong-umd** [comment]
If adding a start page, I think it cannot be named as "start". When we define the workflow pages, start page should not be part of main steps. Maybe we can name it as "Introduction"?

**Comment by xhdong-umd** [comment]
I added an intro page, put some vignette links in it. I also made the icons of menu slightly brighter, otherwise it looks too dim.
![image](https://user-images.githubusercontent.com/25039897/76684194-2f5e2480-65e0-11ea-970d-8a340973b5ab.png)

**Comment by xhdong-umd** [comment]
I also updated the windows installer with R 3.6.3, using newer version of inno setup.

**Comment by jmcalabrese** [comment]
@xhdong-umd Thanks! I see your reasoning for calling it intro instead of start, and will think it over. I agree that the intro/start page shouldn't be part of the  main workflow or analysis guide.

I think we should add a help button to the vignettes box, with an explanation that vignettes are a work in progress, and that, eventually, there will be more beginner friendly ctmmweb vignettes.

**Comment by jmcalabrese** [comment]
@xhdong-umd Below is edited text for the vignette help box:

- The vignettes section is currently a work in progress. In the future, we will develop a series of beginner friendly vignettes specifically for ctmmweb.

- For the time being, we include the vignettes from the ctmm R package, which provide detailed explanations of concepts and theory behind the core analyses supported in ctmmweb. 

- We also provide a simple demo of ctmmweb, as well as a vignette for the more advanced user that demonstrates using ctmmweb from the command line, in combination with the ctmm package.

**Comment by xhdong-umd** [comment]
Master and cloud updated with this and the fix of Speed/Distance guide.

**Comment by jmcalabrese** [comment]
One last little thing...I suggest removing the "Periodic movement models" vignette from the vignette box, as it is not really relevant to ctmmweb.

**Comment by xhdong-umd** [comment]
Updated master and cloud for this.
