### ISSUE TITLE
Built-in dataset import

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#120]
@xhdong-umd in the "Import from ctmm" box on the Import page, could you please change the default so that the "Take sample of" checkbox is NOT checked. 

IIRC, taking a subsample by default was done for our internal testing purposes, to run tests and checks faster. However, I don't think it makes much sense to have this as the default for users. This is especially so given that users will probably want to recreate our jaguar analysis in the upcoming ctmmweb paper, which requires using the full dataset.

**Comment by xhdong-umd** [comment]
Changed. Will push to master with other changes together later.
