### ISSUE TITLE
Documentation for model selection

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#121]
The OUf and OU Omega models are not listed in the models table in the model selection help entry. Please update the table to include these. I remember that this caused some confusion during the Brazil course last year, but I forgot to post an issue about it then.

Also, the models table in the help doesn't render correctly on my system, with the column titles smashed together.

**Comment by xhdong-umd** [comment]
That table was added long time ago and not updated. I cannot find where I got that table now. @chfleming Can you give me some reference or text?

The model table have some unicode symbols. I was using UTF-8 which should be correct. This kind of problem is hard to debug as I didn't see problem in my Mac and windows machine... What locale and language you are using?

**Comment by jmcalabrese** [comment]
@xhdong-umd That table came from the 2016 MEE paper I led ( https://doi.org/10.1111/2041-210X.12559). The OUf and OU Omega models didn't exist then. I believe there is documentation for these new models in ctmm that you could bring over to the webapp and/or @chfleming could provide some.

My locale is US and language is US English.

The issue with the way the table renders is that there is not enough spacing between columns, so that the column titles run together. See attached screenshot.


![table](https://user-images.githubusercontent.com/26653992/78870347-41e44600-7a46-11ea-83b4-8ebdcd223170.png)

**Comment by jmcalabrese** [comment]
@xhdong-umd, @chfleming has there been any follow-up on adding the above-mentioned documentation?

**Comment by xhdong-umd** [comment]
@jmcalabrese @chfleming I'm waiting for the documentation as I don't know about the details. Once they were provided I can update the help text.

**Comment by chfleming** [comment]
Sorry, both are autocorrelated position and autocorrelated velocity, and home range.

For parameters, OUf is $\tau = {\tau,\tau}$, where effectively $\tau_r=\tau_v$, and OUO is $\tau = {\tau,\tau}$ and $\omega>0$.

**Comment by xhdong-umd** [comment]
@chfleming What's the full name of OUf and OUO, like the names in the reference table?

**Comment by chfleming** [comment]
OU in both cases stands for Ornstein-Uhlenbeck, while the 'F', 'f', 'Omega' don't have to mean anything, and can be expressed similarly to the OUF case. Your choices are probably more descriptive.

The omega in the OUO parameterization should be lower case, though.

**Comment by xhdong-umd** [comment]
Updated to this
![image](https://user-images.githubusercontent.com/25039897/80311416-8ba28f80-87ad-11ea-9c29-06493fc31a05.png)
