### ISSUE TITLE
Save progress error

### ISSUE THREAD

**Issue by anaveda** [ctmm-initiative/ctmmweb#122]
Hi,
I am trying to save my session and I am getting this error:

Warning: Error in zip_internal: zip error: `Cannot add file `Report_2020-04-30_15-21-41/home_range_2020-05-01_06-59-51.png` to archive `C:/Users/Adrian/AppData/Local/Temp/RtmpaMim5j/3ea6930ac8c7e8717c5727dcc3fb3216/plot.zip`` in file `zip.c:394`
  [No stack trace available]

I wonder if any of you can help to figured it out. All the best,

Adrian

**Comment by xhdong-umd** [comment]
Which version you are using? Did you try the most recent version in master branch?

**Comment by anaveda** [comment]
R 3.6.2

ctmmweb 0.2.6.9

 

Will try the most recent version. 

Thanks.

 

All the best,

 

=============================================================

Adrián Naveda-Rodríguez

Pho: 662-312-7435

E-mail:  <mailto:adrian.naveda@gmail.com> adrian.naveda@gmail.com

 <https://www.researchgate.net/profile/Adrian_Naveda-Rodriguez> https://www.researchgate.net/profile/Adrian_Naveda-Rodriguez

 <https://publons.com/a/1189620/> https://publons.com/a/1189620/
