### ISSUE TITLE
Issue exporting Occurrence contours 

### ISSUE THREAD

**Issue by P-Reynolds** [ctmm-initiative/ctmmweb#125]
Hello,

I've come across an issue where all my occurrence distribution exports end up being the 95% contour level once exported. Though, I was able to export 50,75,and 95% contours for my home ranges successfully. The 50% contours plots for OD will load and look fine in the ctmmweb app but once I export them into ArcGIS they are always the 95% contour? Even the attribute table for the shapefile has only one row of information and says its the 95% est contour. 

I've tried on multiple different devices with the latest update of the web app. How can I export and download the 50% (or anything other than 95%) for my occurrence distributions? 
Sidenote: the grd format exports come up as invalid datasets when I try to import them into ArcGIS, however the TIFF format works correctly.

Thanks for any advice.
Patrick

**Comment by xhdong-umd** [comment]
Thanks for the report. There is a missed parameter in the export and I'll fix the bug.

**Comment by xhdong-umd** [comment]
@P-Reynolds , can you try with this version? 

`remotes::install_github("ctmm-initiative/ctmmweb", ref = "daily")`

**Comment by xhdong-umd** [comment]
@chfleming , one question about exporting to raster. ctmm::writeRaster will not take level.UD parameter, because raster export doesn't show the contours, right? I wanted to note this in help but want to confirm first.

**Comment by chfleming** [comment]
That's correct.

**Comment by P-Reynolds** [comment]
Thank you, the new version seems to cleared up the problem! ArcGIS still won't accept the .grd raster formats I export saying it is an invalid dataset, not sure if it is just a problem on my end but the TIFF exports upload fine if I need the rasters, so no other problems from me.

Thanks for the help.

**Comment by xhdong-umd** [comment]
@P-Reynolds , `.grd` is a R `raster` package native format, you will need to convert it first before importing into ArcGIS. See `?raster::writeRaster` and this guide [Exporting Rasters from R to ArcGIS](https://terpconnect.umd.edu/~egurarie/research/NWT/Step02b_ExportingRastersToArcGIS.html).

**Comment by P-Reynolds** [comment]
Thanks for the clarification.
