### ISSUE TITLE
Unicode symbol as model summary table column name caused problem in certain platforms

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#128]
I have long suspecting that user locale/encoding will cause some problem with model summary table column names, which have some unicode symbols.

Recently a user met problem with model summary and the `Sys.getlocale("LC_CTYPE")` is `English_United States.1252`. I verified the problem: with this locale the model summary table will have problem with unicode symbol columns.

In this locale I can't find a way to make column names with unicode symbol

```r
Sys.setlocale("LC_CTYPE", "English_United States.1252")
> df <- data.frame("\u0394AICc" = 2)
Warning message:
unable to translate '<U+0394>AICc' to native encoding 
```

I think the fallback solution is to only use ascii names. 

@chfleming how do you think about this?

If we do need to use ascii names, what will be best name for AICc, tau, etc? for example just `dAICc` and `tau`?

**Comment by chfleming** [comment]
Yeah, dAICc, tau, sigma, ...

This is a Windows locale issue?

**Comment by xhdong-umd** [comment]
I'm using windows but my locale have no problem (GBK, Chinese). One user had the problem with English local 1252, and I guess it was windows.

We also had report of tau unit rounding problem in some of students of same class, I suspect it could also be locale problem.

The locale and unicode problem is messy and we have no control of user's locale/settings, so I think the safest way is to use ascii names.

**Comment by xhdong-umd** [comment]
Other than `ΔAICc` and `τ[position]`, is there any other unicode symbol possible in model summary?

**Comment by xhdong-umd** [comment]
I updated the app with `dAICc` and `tau`. And the user no longer have problems.

**Comment by chfleming** [comment]
There are other `tau[something]` and if you change the IC, then there can be other `deltaSOMETHINGS`. I don't think there's anything else beyond that.

**Comment by xhdong-umd** [comment]
All `tau` are replaced. I think I need to add the support of changing IC to see delta, which is another feature you suggested before. I'll look at that one.

**Comment by xhdong-umd** [comment]
As a side note, the ctmm summary of model doesn't have this problem even with the 1252 locale., which is a matrix/array. It seemed that R can handle unicode characters in matrix dimnames, but not in data.frame/data.table column names. I need quite some features from data.table so matrix will not work for my purposes.
