### ISSUE TITLE
calibration data error

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#129]
@chfleming I received an error report from user about the calibration process. I forwarded the email to you so you should have copy of the data.

To reproduce the error:
1. load movement_data
2. load calibration data in 5.Error pane, apply to current
3. there is error in the error plot
```r
Warning: Error in graphics::symbols: invalid symbol parameter
  172: graphics::symbols
  171: utils::getS3method("plot", CLASS)
 170: plot.list
```

What really happened is:
- in 5.Error pane, once calibration data is loaded, I'll use ctmm:::is.calibrated to check if it's pre-calibrated data. If not, I'll use uere.fit to estimate uere from uploaded data. Then uere was applied to telemetry data and update the error plot.
- The user provided calibration data look to be pre-calibrated because it has HDOP,z,VDOP,x,y,VAR.xy,VAR.z columns, but ctmm:::is.calibrated report it as not calibrated. Thus uere.fit was used, then later there is error.

To reproduce above in script:

```r
library(ctmm)

tele_list <- as.telemetry("d:/Work/R/ctmm-shiny/data/movement_data.csv")
cali_tele <- as.telemetry("d:/Work/R/ctmm-shiny/data/calibration_data.csv")
ctmmweb:::is_calibrated(cali_tele)

cali_uere <- ctmm::uere.fit(cali_tele)
uere(tele_list) <- cali_uere 

ctmm::plot(tele_list, error = 2)
```

So my question is:
- Is there problem with this calibration data? Maybe this is calibrated data (with var.xy columns) but not calibration data?
- then is the plot error caused by wrong calibration process or something else?
- I want to confirm these steps in app are correct: if a uploaded calibration data (in step 5.Error pane) is reported as is.calibrated, then I use uere(calibration_data) to apply to telemetry data. Otherwise I'll use uere.fit to estimate first then apply. Is this correct? Calibration concepts is always a little bit tricky for me to grasp.

**Comment by chfleming** [comment]
The error is happening because the "movement_data" are not being calibrated correctly (class mismatch), ...
because they have a different format (`sensor.type='gps'`) than the "calibration_data", ...
because "calibration_data" are not MoveBank formatted, ...
because "calibration_data" look like "movement_data" that have been run through `ctmm` and calibrated already, ...
but the RMS UERE for "calibration_data" is suspiciously large (38 meters) and the same as what you get when treating "movement_data" as calibration data.

**Comment by xhdong-umd** [comment]
@chfleming , Adrián mentioned that the hosted web version doesn't have the error. Out of curiosity I tested and found it's related to ctmm version. By further installing different ctmm versions, I found out that after [this commit](https://github.com/ctmm-initiative/ctmm/commit/d9128cd529772ac5d784d30bf2727dca04ad4e38) there will be error.

Reproducible code if you download the data shared by Adrián 

```r
library(ctmm)
tele_list <- as.telemetry("d:/Work/R/ctmm-shiny/data/Vultures movement/Vultures position Summer 2020 MB.csv")
cali_tele <- as.telemetry("d:/Work/R/ctmm-shiny/data/Vultures movement/Calibration data CTT E-400 MB unit 12340.csv")

# ctmmweb:::is_calibrated(cali_tele)

cali_uere <- ctmm::uere.fit(cali_tele)
uere(tele_list) <- cali_uere 

ctmm::plot(tele_list,
               error = 2)


```

Of course I knew you mentioned before there were some problems in the data, so the error might be expected behavior since the data was not right. I just want you to know this detail.

**Comment by chfleming** [comment]
The error was mine this time. It should be fixed now. I didn't anticipate different fix-type columns sometimes differing and sometimes not, though I should had.

**Comment by xhdong-umd** [comment]
Thanks Chris!
