### ISSUE TITLE
Estimate Overlap of 50% Home Range Contours

### ISSUE THREAD

**Issue by vjmer** [ctmm-initiative/ctmmweb#134]
I want to get an estimate of the amount of overlap between my animals' 50% home range contours. When I click the "Overlap" tab, the numbers that I get in the list are of the 95% home range contours. I can change the Pairwise Plots to show the overlap of the 50% home range contours, but I cannot get the Overlap Values to show 50% contour values. Does anyone know how to get the overlap values to show the 50% home range contour overlap?

Thank you.

**Comment by chfleming** [comment]
We don't implement a geometrical overlap between % coverage areas of a particular %. Instead we implement a statistical overlap measure (the Bhattacharyya coefficient), which obviates the need to choose a % threshold (which the result will be sensitive to) and accounts for non-uniform space use. This measure also returns a quantity proportional to the geometric overlap in cases of uniform space use, where that calculation makes sense.

- https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13027
- https://ctmm-initiative.github.io/ctmm/reference/overlap.html
- https://en.wikipedia.org/wiki/Bhattacharyya_distance

The only % you choose for the overlap estimates is that of the confidence intervals. The overlaps are calculated using the entire density functions.
