### ISSUE TITLE
cant import data

### ISSUE THREAD

**Issue by CandidCritters** [ctmm-initiative/ctmmweb#136]
I can't seem to import data from Movebank.  When I try it directly I get an error.  When I download the file and then try to import the file I also get an error.  I tried this with 3 different studies.  I'll attach the data.
cheers
Roland

[Movebank 220229 - Tsavo Lion Study.csv](https://github.com/ctmm-initiative/ctmmweb/files/7345843/Movebank.220229.-.Tsavo.Lion.Study.csv)
[Movebank 11948467 - NCSU Mammalogy Campus Carnivores.csv](https://github.com/ctmm-initiative/ctmmweb/files/7345844/Movebank.11948467.-.NCSU.Mammalogy.Campus.Carnivores.csv)
<img width="1100" alt="Screen Shot 2021-10-14 at 8 07 17 AM" src="https://user-images.githubusercontent.com/34037047/137314474-762d7b96-e22c-439a-839c-f08f45d46dcd.png">
[Movebank 1573471517 - OC Vultures.csv](https://github.com/ctmm-initiative/ctmmweb/files/7345845/Movebank.1573471517.-.OC.Vultures.csv)

**Comment by xhdong-umd** [comment]
There are various data quality problems in the input files:
- `Movebank.1573471517.-.OC.Vultures.csv` have wrong format of timestamp like `00:53.0`. 

```r
> as.telemetry("e:/Movebank.1573471517.-.OC.Vultures.csv")
0 outlier markings ignored.
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
```

- The other two files have some rows with empty identifier name. This caused some problem in my code when I sorted the individual by names, also we need to identify and access each individual by name. I'll make some changes to assign a temporary name to fix this problem.
