### ISSUE TITLE
No crs function

### ISSUE THREAD

**Issue by yuxin321** [ctmm-initiative/ctmmweb#138]
I met a error. I imported my data (* csv: timestamp; lon; lat; ID). When calculating the home range, there is an error is displayed: no crs function.
How to solve it. I would appreciate it if you could tell me.

**Comment by chfleming** [comment]
Hi @yuxin321 , have you tried updating all of your packages and starting in a fresh session with no other packages loaded? I had one other user report this error and it went away when they updated and restarted fresh.

**Comment by chfleming** [comment]
@yuxin321 if that doesn't solve the issue, then please send me a data example, and I will look into it.

**Comment by yuxin321** [comment]
The issue has not been solved. I send a data example for you email. Thank you very much for the generous help!

**Comment by chfleming** [comment]
@yuxin321 I am not able to reproduce this error, and was able to estimate home ranges. Can you tell me exactly how to reproduce the error, starting in a fresh session with no objects or packages loaded?

**Comment by xhdong-umd** [comment]
This look like some package was not installed properly. How did you run the process, how did you install the packages (ctmmweb and ctmm)?

**Comment by yuxin321** [comment]
Thank you for your answer. According to the following code in R studio.
#install 
if (!require("remotes")) install.packages("remotes")
remotes::install_github("ctmm-initiative/ctmmweb")

# run: ctmmweb
ctmmweb::app()

**Comment by yuxin321** [comment]
> @yuxin321 I am not able to reproduce this error, and was able to estimate home ranges. Can you tell me exactly how to reproduce the error, starting in a fresh session with no objects or packages loaded?
Thank you for your reply. Here are my steps:
1)import my data
2)model selection
3)click "home range" and choose " in same grid..."
and then the error was produced.

**Comment by chfleming** [comment]
Hi @yuxin321 , that is the usual procedure, but I am not able to reproduce the error. 

Are you starting in a clean workspace with no objects loaded in the "Environment" panel of RStudio?

In RStudio Options : General : Basic
* Is "Restore .RData into workspace at startup" unchecked?
* Is "Save workspace to .RData on exit" set to "Never"?

When you click "Tools" "Check for Package Updates", are your packages able to be updated without errors?

This is R version 4.2.1?

I don't think it will matter, but can you also try running:

`remotes::install_github("ctmm-initiative/ctmm")`

**Comment by yuxin321** [comment]
Hi, @chfleming. The error is solved after I upgrade R version to 4.2.1 and reinstall and run ctmm. Thank you very much for the comments!
