### ISSUE TITLE
<simpleError in as.POSIXlt.character(x, tz, ...): character string is not in a standard unambiguous format>

### ISSUE THREAD

**Issue by edwinchiroodza** [ctmm-initiative/ctmmweb#139]
im trying to upload a csv from my PC however i'm getting this error : <simpleError in as.POSIXlt.character(x, tz, ...): character string is not in a standard unambiguous format>

the date is in the format 1.23.22 and time is 12:56:00

I have attached the file for those who may wish to recreate the error

thank you

[v5and6.csv](https://github.com/ctmm-initiative/ctmmweb/files/9990304/v5and6.csv)

**Comment by xhdong-umd** [comment]
ctmmweb is using `ctmm::as.telemetry" in backend to import data.

```r
> ctmm::as.telemetry("d:/v5and6.csv")
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
```

Your date column is not a standard unambiguous date format. Please use or convert to standard ISO date format like `YYYY-MM-DD` `YYYY/MM/DD`.

**Comment by edwinchiroodza** [comment]
Thank you, changed the timestamp format, uploaded successfully
