### ISSUE TITLE
Home range

### ISSUE THREAD

**Issue by 1425890** [ctmm-initiative/ctmmweb#141]
I clicked "Export" and nothing happened.
Why can't my home map come out? Is it because you didn't enter the weight? Who can tell me what I should do?Can the author make a video about the detailed steps of how to draw a complete family map?
![1691031843773](https://github.com/ctmm-initiative/ctmmweb/assets/141293721/ccb00be6-cabf-41e2-86de-90e701a31462)
@xhdong-umd xianghui dong

**Comment by chfleming** [comment]
Hi @1425890 , I just updated `ctmmweb` from the soon to be depreciated `rgdal` package to `terra`. If you update both `ctmm` and `ctmmweb` from Github, then exporting should work again.
