### ISSUE TITLE
initial setting in Vizualisation

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmmweb#42]
I was thinking.

Would it make sense not to have "Others in background" enabled as default to reduce initial load of the application?

**Comment by xhdong-umd** [comment]
This is a pure user preference question, and I don't have strong preference on either way.

For now we haven't collect much user feedbacks yet, so I'm not sure what's best option for majority of user cases. Maybe we can have more responses later and be more clear on this.

Besides, what's the time difference with it on or off? You can turn it off then load data again (you may need to switch to some other data then switch back to trigger changes) to compare the performance.

Another factor related to initial loading is that the work report feature is saving every plot into png now. It will become significantly faster if you turn off the `record actions` option.

**Comment by xhdong-umd** [comment]
Temporarily closed until we have more input and feedbacks on this issue.
