### ISSUE TITLE
Saving cleaned data

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#44]
After the user has gone through the data cleaning steps, it would be useful to have an option where the user can export the cleaned data for future use.

**Comment by xhdong-umd** [comment]
What does the data cleaning refer to? The outlier detection and removal?

**Comment by NoonanM** [comment]
Yes. We've had requests from users who would like to be able to do the outlier detection/removal, and then save the 'clean' data. This would be useful for people with large datasets who might need to spend many hours at that step.

**Comment by xhdong-umd** [comment]
I found I actually save that data already.
- When you click `save_cache` button in the work report page, a list of data objects are saved as `saved.rds`, which can be imported to R. 
- `saved.rds` is a list with item name `data`, which in turn include
  - `input_tele_list`: the original input telemetry object list
  - `tele_list`: the current telemetry object list, for example some outliers can be removed, new time subset may be added.
  - `merged`: list of 
    - `data`: the combined `data.table` of all animals 
    - `info`: the summary table
  - `all_removed_outliers`: all rows that were removed as outliers.
- To make it easier to work, I added a checkbox in work report page `save telemetry data`. With this selected, the `download report as zip` button will save the current telemetry data as a csv and include it in the zip. User can import the csv later.

**Comment by NoonanM** [comment]
That sounds perfect. Thanks for the update.
