### ISSUE TITLE
move help website to separate repo

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#45]
@chfleming @jmcalabrese 
I found the website folder `docs` took 10M, that means the installation of `ctmmweb` need to download a 10M zip even when the real package is less than 1M.

I tried to exclude the website folder from the download, but it's difficult because [I need to deal with different requirements from](https://stackoverflow.com/questions/48330059/how-to-exclude-a-folder-to-be-downloaded-when-hosting-r-package-in-github)
- `devtools::install_github` always download the whole master branch
- github only host website in master or gh-pages branch
- git cannot maintain different .gitignore in different branches, which make it impossible to maintain two branches that with some folder difference.

It seemed that the only good option is to create a separate repo just for website. This means the website url will need to change a little bit. I'm thinking something like
`https://ctmm-initiative.github.io/ctmmwebdoc`

**Comment by xhdong-umd** [comment]
Finally I made it works at [here](https://ctmm-initiative.github.io/ctmmwebdoc).

It took me several hours to do this. Now the package download is less than 1M.

**Comment by chfleming** [comment]
Does `.Rbuildignore` not handle this with:
`^docs$`
`_pkgdown.yml`

**Comment by xhdong-umd** [comment]
That was for the binary package. `install_github` install the package by source, which just download the whole repo zip through github API.

**Comment by xhdong-umd** [comment]
Installing `ctmm` with `install_github` will also download the docs folder, though that is just 2M so it's not too bad. My docs folder have some bigger plots and some maps which took more spaces.
