### ISSUE TITLE
Speed estimation functionality

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#50]
At some point this new feature should probably get its own page in the webapp:

https://ctmm-initiative.github.io/ctmm/reference/speed.html

We are still working on the manuscript at the moment.

**Comment by xhdong-umd** [comment]
@chfleming @NoonanM @jmcalabrese 
I took a look at the speed function and the paper. To add a Speed page,

- Where should we put it? after `home range` page or `occurrence`?
- There are some parameters to the speed function, which ones should be exposed to users? 
  - I think at least `level` and `robust`? Can `level` take multiple values like in home range calculation?
  - Should these parameters apply to all individuals or specified to certain ones? `robust` need to be applied to all individuals.
- I think we can have a table for speed result, maybe also plot it.
- `simulate` can plot a simulated trajectory which seemed to be relate to the speed estimation, do you want to plot that too?

**Comment by chfleming** [comment]
I think home range and occurrence should be kept close.

`robust` is important when the data can barely resolve speeds.

I didn't code `speed()` for multiple `level` values. I'm not sure how much people would be interested in that.

Its important to keep `robust` and `level` the same over all individuals.

If there are going to be `simulate` plots, they should probably be on their own page, I think.

**Comment by chfleming** [comment]
OU models cannot estimate speed. I have an patch coming that will fix this to return `Inf` with a warning instead of bombing out with an error.

**Comment by NoonanM** [comment]
Speed can only be estimated from the OUF and IOU models. Although Chris is implementing some code that returns infinity if another model is used. That should be up on GitHub soon.

**Comment by xhdong-umd** [comment]
In the app, all the home range, overlap, occurrence pages features are based on the models selected in the model summary table in model page.

For speed, if we still use this convention, it's possible to select the OU models and cannot get a result. Should we 
1. still use this design to be consistent with other pages, but some models will not have speed result. User need to select different models to get a result
2. just select all valid models to calculate speed. This will be a little bit different from other pages. And will calculating lots of models taking a lot of time?
3. select the best OUF/IOU models for each individual, this is to ensure only one valid model is selected for one individual so there is no need to calculate all models. But users may want to know speed for some alternative models, so this option is kind of limited (and with option 1 and 2 it's still possible to know speed for every valid model)

**Comment by chfleming** [comment]
Easier and more valid is to return the `Inf` values after my patch.

**Comment by xhdong-umd** [comment]
OK, then we just stick to the design, but return `Inf` for fractal models.

I tested with full data, 6 animals in buffalo dataset each took 60 - 240s to finish. I can try to use parallel, but the total time will be limited by the slowest individual.

**Comment by chfleming** [comment]
The function is parallelized internally as well.

**Comment by xhdong-umd** [comment]
The parallel version did save some time, estimating speed for 6 animals together took 320s.

With sampled data, I meet 2 other types of error:
- `vector memory exhausted (limit reached?)`
- `Sampling distribution does not always resolve velocity, c`


(The code below selected some OU models, just ignore them)
```r
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ctmm, ctmmweb, data.table, ggplot2)
data(buffalo)
# take a 100 point sample from each animal to speed up model fitting etc
data_sample <- pick(buffalo, 100)
# data_sample <- buffalo
collected_data <- collect(data_sample)
# a list of locations data.table/data.frame and information table
loc_data <- collected_data$data
info <- collected_data$info

model_try_res <- par_try_models(data_sample)  # 180s for full buffalo data
model_summary <- summary_tried_models(model_try_res)
model_list <- flatten_models(model_try_res)

# selected_models <- model_list[1:5]
selected_models <- model_list
# selected_tele <- data_sample[c(1, 1, 2, 2, 3)]
selected_tele <- data_sample

# ctmm::speed(selected_models[[1]], data = selected_tele[[1]])
# names(selected_models)[[1]]
# system.time(ctmm::speed(selected_models[[2]], data = selected_tele[[2]]))
# use sampled model, full data
# 80s for full data
system.time(ctmm::speed(selected_models[[1]], data = buffalo[[1]]))  # 141
system.time(ctmm::speed(selected_models[[2]], data = buffalo[[2]]))  # 72
system.time(ctmm::speed(selected_models[[3]], data = buffalo[[3]]))  # 96
system.time(ctmm::speed(selected_models[[4]], data = buffalo[[4]]))  # 60
system.time(ctmm::speed(selected_models[[5]], data = buffalo[[5]]))  # 62
system.time(ctmm::speed(selected_models[[6]], data = buffalo[[6]]))  # 262 full data, 120s sample data Mvubu OUF

# parallel
para_list <- ctmmweb::align_2_list(selected_models, selected_tele)
speed_para <- function(para_list) {
  ctmm::speed(para_list[[1]], para_list[[2]])
}
system.time(ctmmweb::par_lapply(para_list, speed_para))  # 310 

```

```r
> system.time(ctmm::speed(selected_models[[1]], data = buffalo[[1]]))  # 141
Error in speed.ctmm(selected_models[[1]], data = buffalo[[1]]) : 
  Movement model is fractal. Speed cannot be estimated.
Timing stopped at: 0.023 0.001 0.025
> system.time(ctmm::speed(selected_models[[2]], data = buffalo[[2]]))  # 72
  |                                                                                        |   0%Error: vector memory exhausted (limit reached?)
Timing stopped at: 180.7 41.75 224.8
> system.time(ctmm::speed(selected_models[[3]], data = buffalo[[3]]))  # 96
Error in speed.ctmm(selected_models[[3]], data = buffalo[[3]]) : 
  Movement model is fractal. Speed cannot be estimated.
Timing stopped at: 0.001 0 0.001
> system.time(ctmm::speed(selected_models[[4]], data = buffalo[[4]]))  # 60
  |                                                                                        |   0%Error in speed.ctmm(selected_models[[4]], data = buffalo[[4]]) : 
  Sampling distribution does not always resolve velocity, c
Timing stopped at: 0.003 0 0.003
> system.time(ctmm::speed(selected_models[[5]], data = buffalo[[5]]))  # 62
Error in speed.ctmm(selected_models[[5]], data = buffalo[[5]]) : 
  Movement model is fractal. Speed cannot be estimated.
Timing stopped at: 0.001 0 0.001
> system.time(ctmm::speed(selected_models[[6]], data = buffalo[[6]]))  # 262
  |========================================================================================| 100%
   user  system elapsed 
111.514   9.235 120.789 

```

**Comment by xhdong-umd** [comment]
With OUF models selected for each individual, 4 models can be estimated relatively quickly, but 2 of them took a long time or met error `Hessian not negative semidefinite. Try fast=FALSE.`.


```r
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ctmm, ctmmweb, data.table, ggplot2)
data(buffalo)
# take a 100 point sample from each animal to speed up model fitting etc
data_sample <- pick(buffalo, 100)
# data_sample <- buffalo
collected_data <- collect(data_sample)
# a list of locations data.table/data.frame and information table
loc_data <- collected_data$data
info <- collected_data$info

model_try_res <- par_try_models(data_sample)  # 180s for full buffalo data
model_summary <- summary_tried_models(model_try_res)
model_list <- flatten_models(model_try_res)

first_OUF <- c(2, 4, 6, 7, 9, 12)
# selected_models <- model_list[1:5]
selected_models <- model_list[first_OUF]
# selected_tele <- data_sample[c(1, 1, 2, 2, 3)]
selected_tele <- data_sample[first_OUF]

# ctmm::speed(selected_models[[1]], data = selected_tele[[1]])
# names(selected_models)[[1]]
# system.time(ctmm::speed(selected_models[[2]], data = selected_tele[[2]]))
# use sampled model, full data
# 80s for full data
system.time(ctmm::speed(selected_models[[1]], data = buffalo[[1]]))  # 141
system.time(ctmm::speed(selected_models[[2]], data = buffalo[[2]]))  # 72
system.time(ctmm::speed(selected_models[[3]], data = buffalo[[3]]))  # 96
system.time(ctmm::speed(selected_models[[4]], data = buffalo[[4]]))  # 60
system.time(ctmm::speed(selected_models[[5]], data = buffalo[[5]]))  # 62
system.time(ctmm::speed(selected_models[[6]], data = buffalo[[6]]))  # 262
```

```r
> system.time(ctmm::speed(selected_models[[1]], data = buffalo[[1]]))  # 141
  |                |   0%Error: vector memory exhausted (limit reached?)
Timing stopped at: 1296 271.5 1569
> system.time(ctmm::speed(selected_models[[2]], data = buffalo[[2]]))  # 72
  |              |   0%Error in emulate.ctmm(CTMM, data = data, fast = fast, ...) : 
  Hessian not negative semidefinite. Try fast=FALSE.
Timing stopped at: 0.003 0 0.003
> system.time(ctmm::speed(selected_models[[3]], data = buffalo[[3]]))  # 96
  |========================================================================================| 100%
   user  system elapsed 
 31.761   0.735  32.506 
> system.time(ctmm::speed(selected_models[[4]], data = buffalo[[4]]))  # 60
  |========================================================================================| 100%
   user  system elapsed 
 16.712   0.195  16.906 
> system.time(ctmm::speed(selected_models[[5]], data = buffalo[[5]]))  # 62
  |========================================================================================| 100%
   user  system elapsed 
 34.153   0.517  34.681 
> system.time(ctmm::speed(selected_models[[6]], data = buffalo[[6]]))  # 262 full data, 120s sample data Mvubu OUF
  |========================================================================================| 100%
   user  system elapsed 
 34.057   1.749  35.821 
```

**Comment by chfleming** [comment]
I've converted the errors to warnings that return `Inf`.

I don't know about the vector memory warning. Maybe too much parallelization?

**Comment by xhdong-umd** [comment]
The vector memory warning may be caused by some variable increased too much, could be an infinite loop. I found the progress meter started to 4% then rolled back to 0% and stopped there, until it quits.

**Comment by xhdong-umd** [comment]
With the `Inf` result, the row name seemed to be using the short unit name while others using long unit name.

```r
> res[[2]]
            low  ML high
speed (m/s)   0 Inf  Inf
> res[[4]]
                             low         ML       high
speed (meters/second) 0.04154656 0.04953695 0.05751277
```

**Comment by xhdong-umd** [comment]
What's the difference between the `speed` column in model summary table and estimated speed? I think I need to add some help text or use different terms for these two to avoid confusion.

Should we also include the speed column from model summary in speed page for comparison?

**Comment by chfleming** [comment]
Its analogous to the difference between the model fit area and the AKDE area. The former is a Gaussian estimate and the latter is non-parametric (though with the assumption that the fitted model approximates the autocorrelation structure).

**Comment by chfleming** [comment]
They are both estimates. The first is a Gaussian RMS speed. The second is a non-parametric mean speed.

**Comment by xhdong-umd** [comment]
With the sampled data, speed function on first OUF model will error after vector memory limit reached. I profiled the code and this is the result

<img width="1057" alt="screen shot 2018-09-27 at 2 38 55 pm" src="https://user-images.githubusercontent.com/25039897/46167232-4598e900-c263-11e8-87f4-70cd25273759.png">

<img width="1061" alt="screen shot 2018-09-27 at 2 39 28 pm" src="https://user-images.githubusercontent.com/25039897/46167240-4af63380-c263-11e8-89d3-5d2bd08a61e8.png">


Most time and memory are spent on `smoother` and `fill.data` in `simulate.ctmm`. The memory table is showing the allocated memory in right side, and deallocated memory on left side as negative values (when memory was released or garbage collected).

Maybe some situation caused the abnormal memory allocation in `fill.data`?

The profile result is [here](https://drive.google.com/file/d/1_myY8pJQTxhqqRwArr1vdD6_ndV0q5AU/view?usp=sharing). You can load it with `profvis` package installed. 

The code to reproduce the result:

```r
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ctmm, ctmmweb, data.table, ggplot2)
data(buffalo)
# take a 100 point sample from each animal to speed up model fitting etc
data_sample <- pick(buffalo, 100)
collected_data <- collect(data_sample)
# a list of locations data.table/data.frame and information table
loc_data <- collected_data$data
info <- collected_data$info

model_try_res <- par_try_models(data_sample)  # 180s for full buffalo data
model_summary <- summary_tried_models(model_try_res)
model_list <- flatten_models(model_try_res)

first_OUF <- c(2, 4, 6, 7, 9, 12)  # except first one, which will halt
selected_models <- model_list[first_OUF]
selected_tele <- data_sample
profvis::profvis({
  ctmm::speed(selected_models[[1]], data = selected_tele[[1]])
})
```

**Comment by chfleming** [comment]
Thanks. I will look into this. I'm in the middle of some other coding at the moment.

**Comment by xhdong-umd** [comment]
Do you think it'll be useful to show both Gaussian RMS speed and the non-parametric mean speed in same table in the speed page?

**Comment by chfleming** [comment]
I do not.

**Comment by xhdong-umd** [comment]
I implemented the basic functionality of speed page. It's quite similar to overlap page with a table showing result, and a plot showing values.

<img width="655" alt="screen shot 2018-10-02 at 12 58 55 pm" src="https://user-images.githubusercontent.com/25039897/46364188-15768f00-c643-11e8-94ac-b97640d91ded.png">

To help user mapping rows in table to value in plot, the plot and table are sorted in same order (if you sort the table or search the table with keywords, plot will also update), and the selected rows in table will be highlighted in plot with different color.

The result table theme is made to be consistent with other model summary pages, i.e.
- animal identity columns in same color theme throughout the app
- the other columns are colored by model type, which was the theme in model/home range table. This is less useful here but I don't want to introduce another theme and confuse users.

**Comment by NoonanM** [comment]
Looks good. It's a straightforward analysis, so the page probably doesn't need anything more than this.

**Comment by chfleming** [comment]
Should be fixed now.

**Comment by xhdong-umd** [comment]
For the distance travelled tab, there will be a table including duration and distance travelled. We can also have a plot. 

Do you want 
- a similar plot with speed, i.e. distance travelled with CI range in x, model name in y
- or a scatter plot with duration in x, distance travelled in y?

**Comment by xhdong-umd** [comment]
I implemented the distance tab with the scatter plot option. To make the label shorter I only used the model number and animal name. Selected rows will be highlighted with a different color. The table color theme is same with the model summary table, i.e. colored by model type.

<img width="887" alt="screen shot 2018-10-11 at 11 42 29 am" src="https://user-images.githubusercontent.com/25039897/46816413-ee0e7900-cd4a-11e8-8b0f-2bf0a032c066.png">

<img width="887" alt="screen shot 2018-10-11 at 11 42 35 am" src="https://user-images.githubusercontent.com/25039897/46816417-f1a20000-cd4a-11e8-8e2f-1566529834cd.png">

**Comment by xhdong-umd** [comment]
The help text and the web app is also updated.

**Comment by xhdong-umd** [comment]
I'm experimenting with running speed in parallel inside each individual instead of on each individual, this should improve the performance as assign cores by individual will not be the most ideal balanced assignment.

However I often found it stops without changes in progress bar.

```r
library(ctmm)
library(ctmmweb)
data(buffalo)
data_sample <- pick(buffalo, 100)
collected_data <- collect(data_sample)
model_try_res <- par_try_models(data_sample)  # 180s for full buffalo data
model_summary <- summary_tried_models(model_try_res)
model_list <- flatten_models(model_try_res)

# only pick OUF models, others may not be available for speed()
first_OUF <- model_summary[stringr::str_detect(model_type, "OUF"), model_no[[1]], by = identity][, V1]

selected_models <- model_list[first_OUF]
selected_tele <- data_sample

system.time(res <-
lapply(1:length(selected_models), function(i) {
  print(i)
  ctmm::speed(selected_models[[i]], selected_tele[[i]],
              level=0.95, robust=FALSE, cores = -1)
})
)
```

I run this several times, most of the time the progress bar stop at some point for a long time. It did finish successfully once. 

Compare to run parallel for individuals:

```r
para_list <- ctmmweb::align_lists(selected_models, selected_tele,
                     rep_len(0.95, length.out = length(selected_models)),
                     rep_len(FALSE, length.out = length(selected_models))
                                        )
par_speed <- function(para_list) {
  ctmm::speed(para_list[[1]], para_list[[2]], 
              level = para_list[[3]], 
              robust = para_list[[4]],
              units = FALSE)
}
system.time(res <- ctmmweb::par_lapply(para_list, par_speed))
```

This finished properly, though there is an error on first model
<img width="556" alt="screen shot 2019-02-15 at 1 10 22 pm" src="https://user-images.githubusercontent.com/25039897/52875745-1526ee00-3123-11e9-9a52-ce5a002ba607.png">

```
[1] "Error in grad.default(fn, PAR) : \n  function returns NA at 2153.84281623739.55277686738567e-056.33635657220362e-0676.44975094961490.000100001456446245 distance from x.\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in grad.default(fn, PAR): function returns NA at 2153.84281623739.55277686738567e-056.33635657220362e-0676.44975094961490.000100001456446245 distance from x.>
```

**Comment by NoonanM** [comment]
I've ran into that issue a lot as well. My best guess is that it has to do with paralellisation in R on a Mac, as opposed to a bug in the speed function. I've found that, on a mac, there are times when setting the cores to -1 doesn't properly tell the process to use the correct number of cores. If you try a specific number (e.g., cores = 2) it will perform better.

**Comment by xhdong-umd** [comment]
I was using `parallel::detectCores(logical = FALSE)` so it will only count physical cores. I noticed ctmm didn't use that parameter so it will report double cores because of hyper threading.

In my macbook speed with `-2` was using 6 cores where there is only 4 physical cores. Maybe this should be modified?

**Comment by chfleming** [comment]
Okay, I wasn't aware that using hyperthreads was bad, but reading the explanation on Wikipedia, it makes sense that there would be no benefit for computational problems like this. I can change that.

Does the error also happen with `cores=1`?

**Comment by xhdong-umd** [comment]
I did have the problem of progress stopped for long time with cores=2.

I think there should not be problem with cores=1, as that's the case of parallel over individuals(one core on each case)
