### ISSUE TITLE
Export raster files

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#51]
I have received a feature request to be able to export raster files like with `writeRaster()` in `ctmm`. This could probably be a button like the export shapefile button in the home-range page.

**Comment by xhdong-umd** [comment]
I assume this is for shape files export, and I can just export the native raster file format with `ctmm::writeRaster(UD, filename)`, right?

Since the shape file export is already a zip, I can just add the raster file into the zip so that export button will export both formats.

**Comment by chfleming** [comment]
That's the right command. Shapefiles are a different format/information.

Some people are going to want to save their rasters in GeoTiff format, which would be inferred by the extension of `filename`, so some separate options will need to be present.

Also, shapefiles are usually multiple files (with specific names) in one directory. That probably doesn't need to be mixed up with the placement of the raster.

**Comment by xhdong-umd** [comment]
OK, so we will need a separate button, or use a checkbox to switch between shapefile and raster file.

For file format, shiny probably doesn't support a predefined file type list. We can either

- let user input file name include extension, and infer file type from extension
- provide some checkbox for common file types, that will take more space.

**Comment by chfleming** [comment]
`writeRaster` will automatically infer the file type from `filename`. `filename` just needs to be able to be user specified.

**Comment by xhdong-umd** [comment]
Yes I knew that. I was just wondering if we should also provide some checkbox, or just use filename inferring.

**Comment by chfleming** [comment]
At minimum, I would supply a working default, like `filename=soandso.tif`.

**Comment by xhdong-umd** [comment]
The shiny downloadhandler works in a special way:
- the filename in download dialog can be prepared with a default name, user can modify it
- the actual file is written somewhere first, then copied to the file path defined in the download dialog.

The file writing process don't know about the filename (it finished before the file name change), so the user provided filename extension cannot be used to infer file type. We have to use some checkbox to determine the file type, and only let user provide file name without extension.

**Comment by xhdong-umd** [comment]
I combined the shapefile and various raster format in one dialog. Clicking `export` will have this pop up:

<img width="626" alt="screen shot 2018-02-28 at 4 05 41 pm" src="https://user-images.githubusercontent.com/25039897/36813093-5c5490c6-1ca1-11e8-92b2-cc93388678b4.png">

Select one format, click `save` will export that format as zip.

We can provide more formats supported by raster, but I think the native raster and tif are mostly used. User can always convert to any other format with raster output. If you think any other format worth to be listed, I can add it easily.

**Comment by kjklauder** [comment]
This is super slick! I love it! Would there be any way for users to be able to select the desired resolution of the rasters? Selecting & exporting multiple individuals at once does produce a consistent cell size, which is good, but being able to dictate the cell size would improve applicability and facilitate consistency between batches.

**Comment by chfleming** [comment]
Functionality is required in `ctmm` to adjust the grid (beyond a relative resolution argument). You can raise an issue there and I can put it on the TODO list:

https://github.com/ctmm-initiative/ctmm/issues/

**Comment by kjklauder** [comment]
One more note on this - it might be good to alert users to the fact that the % Contour level of Home Range selection menu does not apply to generated rasters.

**Comment by xhdong-umd** [comment]
Thanks for the suggestion, how about this?

<img width="619" alt="screen shot 2018-03-16 at 2 49 07 pm" src="https://user-images.githubusercontent.com/25039897/37539124-3a94b828-2929-11e8-8073-34a0da698ca9.png">

**Comment by kjklauder** [comment]
I think that works fine! Thanks!
