### ISSUE TITLE
export shapefile failure

### ISSUE THREAD

**Issue by kjklauder** [ctmm-initiative/ctmmweb#52]
The export shapefile process does not seem to be working correctly, based on testing it with the buffalo data. It does work correctly from the hosted app. I am running R version 3.4.3 (2017-11-30), with a fresh install of ctmmweb minutes ago. 
The following appears when attempting to export a shapefile for Gabs, after clicking the button:
![image](https://user-images.githubusercontent.com/36777330/36619277-c54f0648-189a-11e8-8302-b7c1729c0c88.png)
The file produced is of uncertain type. When opened with notepad it is mostly gibberish.

**Comment by xhdong-umd** [comment]
It's because the RStudio embedded browser has compatibility problem with the download dialog. The file name is supposed to be named as `shapefile-timestamp.zip`. If you rename it into something with `zip` extension you will find it's a zip.

I probably should make the warning in readme more obvious.

**Comment by NoonanM** [comment]
When exporting as an ESRI shapefile, an error message is coming up that the ap couldn't find the function`get_hr_levels`

**Comment by xhdong-umd** [comment]
It was a leftover that I forgot to change. I have fixed it but need to wait current task finish to push the update.

**Comment by xhdong-umd** [comment]
I updated the repo for this. Note I'm working on a lot of changes at the same time so the most up to date version may have problems. 

Usually I only push change after features are stable, recently there are too many tasks running at the same time so some changes are pushed without enough test.
