### ISSUE TITLE
Error when running multiple modelling

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmmweb#53]
Hi.

I get this error when trying to model 49 animal in one go:

> app()

Listening on http://127.0.0.1:4789
[2018-02-28 11:12:55] App started  
[2018-02-28 11:12:55] ## Import Data  
[2018-02-28 11:12:55] Recording is On  
[2018-02-28 11:12:55] Error message directed to console  
[2018-02-28 11:12:55] Parallel mode enabled 
[2018-02-28 11:13:15] Logged in Movebank as 
	sauidrift 
[2018-02-28 11:13:26] Movebank data downloaded 
	70397061 
Maximum speed of 0.932 m/s observed in 71608843
Minimum sampling interval of 60 minutes in 71608843
Maximum speed of 0.675 m/s observed in 71608847
Minimum sampling interval of 60 minutes in 71608847
Maximum speed of 2.77 m/s observed in 71608850
Minimum sampling interval of 60 minutes in 71608850
Maximum speed of 2.77 m/s observed in 71608853
Minimum sampling interval of 60 minutes in 71608853
Maximum speed of 0.998 m/s observed in 71608856
Minimum sampling interval of 60 minutes in 71608856
Maximum speed of 3.11 m/s observed in 71608859
Minimum sampling interval of 60 minutes in 71608859
Maximum speed of 0.912 m/s observed in 71608862
Minimum sampling interval of 60 seconds in 71608862
Maximum speed of 2.79 m/s observed in 71608865
Minimum sampling interval of 60 minutes in 71608865
Maximum speed of 0.948 m/s observed in 71608868
Minimum sampling interval of 60 minutes in 71608868
Maximum speed of 0.947 m/s observed in 71608871
Minimum sampling interval of 60 minutes in 71608871
Maximum speed of 2.79 m/s observed in 71608874
Minimum sampling interval of 60 minutes in 71608874
Maximum speed of 2.77 m/s observed in 71608877
Minimum sampling interval of 60 minutes in 71608877
Maximum speed of 0.0402 m/s observed in 71608881
Minimum sampling interval of 22 hours in 71608881
Maximum speed of 0.614 m/s observed in 71608884
Minimum sampling interval of 60 minutes in 71608884
Maximum speed of 0.573 m/s observed in 71608887
Minimum sampling interval of 60 minutes in 71608887
Maximum speed of 1.05 m/s observed in 71608890
Minimum sampling interval of 30 minutes in 71608890
Maximum speed of 1.62 m/s observed in 71608893
Minimum sampling interval of 30 minutes in 71608893
Maximum speed of 1.2 m/s observed in 71608896
Minimum sampling interval of 30 minutes in 71608896
Maximum speed of 2.97 m/s observed in 71608899
Minimum sampling interval of 30 minutes in 71608899
Maximum speed of 1.14 m/s observed in 71608902
Minimum sampling interval of 30 minutes in 71608902
Maximum speed of 0.98 m/s observed in 71608905
Minimum sampling interval of 30 minutes in 71608905
Maximum speed of 2.81 m/s observed in 71610139
Minimum sampling interval of 34 minutes in 71610139
Maximum speed of 0.994 m/s observed in 71610143
Minimum sampling interval of 60 minutes in 71610143
Maximum speed of 1.86 m/s observed in 71610146
Minimum sampling interval of 60 minutes in 71610146
Maximum speed of 2.91 m/s observed in 71610149
Minimum sampling interval of 60 minutes in 71610149
Maximum speed of 0.554 m/s observed in 71610152
Minimum sampling interval of 33 minutes in 71610152
Maximum speed of 0.648 m/s observed in 71610155
Minimum sampling interval of 5 minutes in 71610155
Maximum speed of 2.98 m/s observed in 71610158
Minimum sampling interval of 24 minutes in 71610158
Maximum speed of 1.57 m/s observed in 71610161
Minimum sampling interval of 60 minutes in 71610161
Maximum speed of 1.54 m/s observed in 71610164
Minimum sampling interval of 60 minutes in 71610164
Maximum speed of 2.82 m/s observed in 71610167
Minimum sampling interval of 60 minutes in 71610167
Maximum speed of 0.751 m/s observed in 71610170
Minimum sampling interval of 60 minutes in 71610170
Maximum speed of 1.99 m/s observed in 71610173
Minimum sampling interval of 60 minutes in 71610173
Maximum speed of 1.18 m/s observed in 71610176
Minimum sampling interval of 60 minutes in 71610176
Maximum speed of 1.99 m/s observed in 71610179
Minimum sampling interval of 60 minutes in 71610179
Maximum speed of 2.89 m/s observed in 71610182
Minimum sampling interval of 60 minutes in 71610182
Maximum speed of 0.755 m/s observed in 71610185
Minimum sampling interval of 60 minutes in 71610185
Maximum speed of 4.72 m/s observed in 71610188
Minimum sampling interval of 30 minutes in 71610188
Maximum speed of 5.25 m/s observed in 71610191
Minimum sampling interval of 30 minutes in 71610191
Maximum speed of 4.35 m/s observed in 71610194
Minimum sampling interval of 30 minutes in 71610194
Maximum speed of 4.71 m/s observed in 71610197
Minimum sampling interval of 30 minutes in 71610197
Maximum speed of 7.08 m/s observed in 71610200
Minimum sampling interval of 60 seconds in 71610200
Maximum speed of 0.923 m/s observed in 71610203
Minimum sampling interval of 60 seconds in 71610203
Maximum speed of 2.84 m/s observed in 71610206
Minimum sampling interval of 30 minutes in 71610206
Maximum speed of 4.65 m/s observed in 71610209
Minimum sampling interval of 30 minutes in 71610209
Maximum speed of 6.93 m/s observed in 71610212
Minimum sampling interval of 30 minutes in 71610212
Maximum speed of 4.63 m/s observed in 71610215
Minimum sampling interval of 30 minutes in 71610215
Maximum speed of 7.19 m/s observed in 71610218
Minimum sampling interval of 30 minutes in 71610218
Maximum speed of 5.26 m/s observed in 71610221
Minimum sampling interval of 30 minutes in 71610221
[2018-02-28 11:15:37] Input data updated  
[2018-02-28 11:15:37] Movebank data imported 
	70397061 
[2018-02-28 11:15:37] ## Visualization  
[2018-02-28 11:15:37] Current selected individuals 
	   identity            start              end   interval   duration points
	1: 71608843 2013-06-14 15:00 2013-09-02 14:00 60 minutes 2.7 months   1919
	2: 71608847 2013-06-08 12:00 2013-09-05 17:00 60 minutes   3 months   2136
	3: 71608850 2013-06-14 14:00 2013-09-02 15:00 60 minutes 2.7 months   1920
	4: 71608853 2013-06-14 14:00 2013-09-02 15:00 60 minutes 2.7 months   1910
	5: 71608856 2013-06-09 09:00 2013-08-11 13:00 60 minutes 2.1 months   1517
	6: 71608859 2013-06-10 16:00 2013-09-02 15:00 60 minutes 2.8 months   2008 
[2018-02-28 11:15:38] saving plot as 
	plot_2_overview_2018-02-28_11-15-38.png 
Saving 22.5 x 8.33 in image
   user  system elapsed 
  6.206   0.201   6.462 
[2018-02-28 11:15:50] saving plot as 
	plot_5_histogram_2018-02-28_11-15-50.png 
Saving 22.5 x 3.89 in image
   user  system elapsed 
  1.393   0.083   1.561 
[2018-02-28 11:15:53] Current selected individuals 
	    identity            start              end   interval   duration points
	 1: 71608843 2013-06-14 15:00 2013-09-02 14:00 60 minutes 2.7 months   1919
	 2: 71608847 2013-06-08 12:00 2013-09-05 17:00 60 minutes   3 months   2136
	 3: 71608850 2013-06-14 14:00 2013-09-02 15:00 60 minutes 2.7 months   1920
	 4: 71608853 2013-06-14 14:00 2013-09-02 15:00 60 minutes 2.7 months   1910
	 5: 71608856 2013-06-09 09:00 2013-08-11 13:00 60 minutes 2.1 months   1517
	 6: 71608859 2013-06-10 16:00 2013-09-02 15:00 60 minutes 2.8 months   2008
	 7: 71608862 2013-06-10 17:00 2013-08-21 02:19 60 minutes 2.4 months   1773
	 8: 71608865 2013-06-10 17:00 2013-09-02 15:00 60 minutes 2.8 months   2006
	 9: 71608868 2013-06-08 14:00 2013-09-10 15:00 60 minutes 3.2 months   2233
	10: 71608871 2013-06-08 15:00 2013-09-10 15:00 60 minutes 3.2 months   2224
	11: 71608874 2013-06-14 15:00 2013-09-02 15:00 60 minutes 2.7 months   1914
	12: 71608877 2013-06-10 17:00 2013-09-02 15:00 60 minutes 2.8 months   2005
	13: 71608881 2013-06-08 11:00 2013-06-09 09:00   22 hours   22 hours      2
	14: 71608884 2013-06-08 15:00 2013-09-04 14:00 60 minutes   3 months   2102
	15: 71608887 2013-06-08 15:00 2013-09-05 16:00 60 minutes   3 months   2133
	16: 71608890 2014-06-15 13:00 2014-09-08 12:00 30 minutes 2.9 months   4028
	17: 71608893 2014-06-16 10:00 2014-09-06 15:00 30 minutes 2.8 months   3781
	18: 71608896 2014-06-16 10:00 2014-09-07 15:00 30 minutes 2.8 months   3990
	19: 71608899 2014-06-15 18:30 2014-09-04 15:00 30 minutes 2.7 months   3857
	20: 71608902 2014-06-15 13:00 2014-09-08 12:00 30 minutes 2.9 months   4023
	21: 71608905 2014-06-15 13:00 2014-09-06 14:30 30 minutes 2.8 months   3983
	22: 71610139 2013-06-23 18:26 2013-09-11 13:00 60 minutes 2.7 months   1902
	23: 71610143 2013-06-12 19:00 2013-09-14 12:00 60 minutes 3.2 months   2140
	24: 71610146 2013-06-20 12:00 2013-09-18 19:00 60 minutes 3.1 months   2144
	25: 71610149 2013-06-12 20:00 2013-09-17 14:00 60 minutes 3.3 months   2151
	26: 71610152 2013-06-23 17:27 2013-09-05 16:00 60 minutes 2.5 months   1700
	27: 71610155 2013-06-23 17:17 2013-09-07 22:00 60 minutes 2.6 months   1642
	28: 71610158 2013-06-10 10:13 2013-09-19 22:00 60 minutes 3.4 months   2340
	29: 71610161 2013-06-20 11:00 2013-09-19 03:00 60 minutes 3.1 months   2119
	30: 71610164 2013-06-20 11:00 2013-09-18 22:00 60 minutes 3.1 months   2143
	31: 71610167 2013-06-10 10:00 2013-09-19 15:00 60 minutes 3.4 months   1726
	32: 71610170 2013-06-20 12:00 2013-09-19 01:00 60 minutes 3.1 months   2117
	33: 71610173 2013-06-20 11:00 2013-09-19 03:00 60 minutes 3.1 months   2114
	34: 71610176 2013-06-20 11:00 2013-09-18 21:00 60 minutes 3.1 months   2118
	35: 71610179 2013-06-20 13:00 2013-09-19 03:00 60 minutes 3.1 months   2106
	36: 71610182 2013-06-12 19:00 2013-09-15 14:00 60 minutes 3.2 months   2147
	37: 71610185 2013-06-12 19:00 2013-09-18 04:00 60 minutes 3.3 months   2289
	38: 71610188 2014-06-15 17:00 2014-09-11 23:00 30 minutes   3 months   4139
	39: 71610191 2014-06-14 23:00 2014-09-11 10:30 30 minutes   3 months   4195
	40: 71610194 2014-06-14 23:00 2014-09-11 23:00 30 minutes   3 months   4247
	41: 71610197 2014-06-15 15:10 2014-09-11 23:00 30 minutes   3 months   4188
	42: 71610200 2014-06-26 22:00 2014-08-17 06:21 30 minutes 1.7 months   2462
	43: 71610203 2014-06-14 23:00 2014-08-29 15:04 30 minutes 2.6 months   3624
	44: 71610206 2014-06-14 23:00 2014-09-11 11:00 30 minutes   3 months   4245
	45: 71610209 2014-06-15 16:30 2014-09-11 23:00 30 minutes   3 months   4145
	46: 71610212 2014-06-30 20:30 2014-09-11 23:00 30 minutes 2.5 months   3429
	47: 71610215 2014-06-15 16:30 2014-09-11 14:30 30 minutes   3 months   4152
	48: 71610218 2014-06-15 16:30 2014-09-11 23:00 30 minutes   3 months   4233
	49: 71610221 2014-06-14 23:00 2014-09-11 11:00 30 minutes   3 months   4244
	    identity            start              end   interval   duration points 
[2018-02-28 11:15:54] saving plot as 
	plot_2_overview_2018-02-28_11-15-54.png 
Saving 22.5 x 8.33 in image
   user  system elapsed 
  9.622   0.411  10.171 
[2018-02-28 11:16:13] saving plot as 
	plot_5_histogram_2018-02-28_11-16-13.png 
Saving 22.5 x 3.89 in image
   user  system elapsed 
  6.239   0.421   7.252 
[2018-02-28 11:16:27] ## Model Selection  
[2018-02-28 11:16:35] saving plot as 
	vario_2018-02-28_11-16-35.png 
[2018-02-28 11:16:38] Trying different models...  
running parallel with mclapply in cluster of 16 
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480).
OMP: Hint: Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
   user  system elapsed 
  0.547   0.647   0.293 
Warning: Error in [.data.table: Column 1 of j's result for the first group is NULL. We rely on the column types of the first result to decide the type expected for the remaining groups (and require consistency). NULL columns are acceptable for later groups (and those are replaced with NA of appropriate type and recycled) but not for the first. Please use a typed empty vector instead, such as integer() or numeric().
Stack trace (innermost first):
    76: [.data.table
    75: [
    74: ctmmweb:::model_try_res_to_model_list_dt
    73: <reactive:summary_models> [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ctmmweb/app/server.R#1744]
    60: summary_models
    59: I_null
    58: invokeRemote
    57: DT::selectRows
    56: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ctmmweb/app/server.R#1738]
     2: shiny::runApp
     1: app

Warning: Error in [.data.table: Column 1 of j's result for the first group is NULL. We rely on the column types of the first result to decide the type expected for the remaining groups (and require consistency). NULL columns are acceptable for later groups (and those are replaced with NA of appropriate type and recycled) but not for the first. Please use a typed empty vector instead, such as integer() or numeric().
Stack trace (innermost first):
    88: <Anonymous>
    87: stop
    86: summary_models
    85: copy
    84: exprFunc [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ctmmweb/app/server.R#1805]
    83: widgetFunc
    82: func
    81: origRenderFunc
    80: renderFunc
    79: origRenderFunc
    78: output$tried_models_summary
     2: shiny::runApp
     1: app

**Comment by xhdong-umd** [comment]
This is a known bug related to data.table, R 3.4, parallel. You can try to restart the R session and try again, most times when it  will be gone. 

You can also turn off the parallel mode in first box of first page as a temporary workaround.

**Comment by xhdong-umd** [comment]
I added some error message to suggest restart R session in this case.
