### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#55]
When you sort columns based on any of the numerical columns (e.g., area tau position, tau velocity, overlap, etc...) it sorts based on all columns, including the confidence intervals. This means confidence intervals become disconnected from their point estimates, making the table hard to interpret. I think sort should only be applied to the ML estimates, and the CIs should just follow those as appropriate.

**Comment by xhdong-umd** [comment]
I think you are referring to the model summary table 

<img width="841" alt="screen shot 2018-03-20 at 4 11 32 pm" src="https://user-images.githubusercontent.com/25039897/37680138-62bfbbc6-2c59-11e8-8df9-9ed9aa1f3e13.png">

Actually this is far from perfect
- all the columns with a unit are text, not numerical values. So the sort above put 10.2 below 1.4. The only way to solve this is to put unit in another column, like the table in outlier page

<img width="852" alt="screen shot 2018-03-20 at 4 13 21 pm" src="https://user-images.githubusercontent.com/25039897/37680222-a4f23b9a-2c59-11e8-8fda-7715f3ec0289.png">

  However that will make this table wider, more difficult to read.

- As long as the CI values are in rows, the sorting feature of the table cannot make CIs bundled together. Unless you move CI values to columns, that means 2 more columns for every value column, which will be 12 more columns. I didn't find a better format yet. We simply have too many information to present.

**Comment by chfleming** [comment]
We should be able to move the unit information to a second header row or to the footer, right?

**Comment by NoonanM** [comment]
Would it work to have a second data.frame hidden in the background that doesn't have CIs, and sort based on that?

**Comment by xhdong-umd** [comment]
@chfleming I'm not sure what the header/footer row means.

@NoonanM You can use the check box to hide CI

<img width="868" alt="screen shot 2018-03-20 at 5 42 04 pm" src="https://user-images.githubusercontent.com/25039897/37684325-115bf544-2c66-11e8-98b2-1144ce6f1983.png">

**Comment by NoonanM** [comment]
Yeah, I know you can hide the CIs. I was suggesting having a second copy of the table in the global environment, that the user doesn't see, but that has numeric values without units, or CIs. When the user hits sort, it first applies to the hidden table, then transfers the sorting to the displayed table (since the names should be the same). It's a bit hacky though.

**Comment by xhdong-umd** [comment]
The sort is built-in feature of shiny DT, I don't think you can make the sort act on a hidden table then transfer back to displayed table. There are also all other features, like the filtering by search field.

I sometimes had some hidden columns in table that doesn't show up in app, but you cannot sort on hidden columns.

**Comment by xhdong-umd** [comment]
@chfleming I realized what do you mean on units to header rows. 

If all rows will have same unit, we can make the column to be pure numeric and put unit in column name. If I'm remembering correct we are using same units for all rows.

Though to put unit name in column name will make them dynamic and difficult to work with. I'll look if this can be solved.

**Comment by chfleming** [comment]
The top row in bold "identity" through "speed" is the table header. JS DataTables (I'm pretty sure that's what this is based on) can have additional header rows and footer rows (a bottom bold row). So the unit label (like "km") could be moved to a second header row or the footer row to save horizontal space.

**Comment by xhdong-umd** [comment]
It's possible to make a second header/footer in DT, but some columns don't have a unit and that will make the footer look bad.

I have converted the columns and added units label to column name. I put the units at second line, so the column will not take extra horizontal space, and it's easer to read.

<img width="982" alt="screen shot 2018-03-22 at 4 32 49 pm" src="https://user-images.githubusercontent.com/25039897/37796992-fc270dc8-2dee-11e8-8622-27a0c25185f3.png">

This method is better than previous treatment, I'll try to also apply it to other tables in app if appropriate.

**Comment by xhdong-umd** [comment]
Previously the data summary table in visualization page calculated the duration of each animal individually, so the units was the best unit for animal self, this could make the table using different time units.

<img width="682" alt="screen shot 2018-03-22 at 4 45 59 pm" src="https://user-images.githubusercontent.com/25039897/37797555-860f17dc-2df0-11e8-8f27-afe6e4088396.png">

I think we should change it to use consistent units, and make them to be numeric so sort will work.

**Comment by NoonanM** [comment]
I agree that units should be held consistent between individuals.

**Comment by xhdong-umd** [comment]
Now the data summary table can be sorted properly. And the plots also respond to the sort/filter of the table.

<img width="764" alt="screen shot 2018-03-23 at 12 30 23 pm" src="https://user-images.githubusercontent.com/25039897/37841388-0cccfd20-2e96-11e8-8fee-8def557f814d.png">

<img width="766" alt="screen shot 2018-03-23 at 12 31 08 pm" src="https://user-images.githubusercontent.com/25039897/37841418-1743e62e-2e96-11e8-8fa3-b56f6a8770d1.png">

**Comment by xhdong-umd** [comment]
The columns order in above was changed accidentally, now it has been fixed
