### ISSUE TITLE
Potential Feature: Data Preparation

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#56]
I know we currently assume Movebank file formats, but many users might not have their data in that format. Would it be useful to provide users with a GUI to help get their data in the right format? For example, converting time stamps and moving between UTM and latlong is fairly easy to do via command line, but can be challenging in GUIs such as excel. Adding a data preparation page could be useful for users not familiar with Movebank, or with data in non-conventional formats that might otherwise be difficult to work with.

**Comment by chfleming** [comment]
I'm almost positive Movebank has a GUI for this, including specific tools to make sure the timestamps are formatted correctly. Also, I think its good to push people through Movebank.

**Comment by xhdong-umd** [comment]
If the data preparation steps can be predicted then this is possible. My experience with bad data is that they can have all kinds of problems, and you often need to deal with them case by case, not in an automated approach.

**Comment by chfleming** [comment]
So you are talking about a pre-Movebank preparation step?

**Comment by NoonanM** [comment]
Yeah, pre-Movebank was what I was thinking. Essentially, I was thinking of a date-time converter where the user can select a date format and it will convert it to the right format, and a something that can work with locations that aren't in lat-long.

Movebank does have some form of online GUI, but you can only use it when you're uploading your data, which some people might not want to do until after the cleaning, and data prep stages?

**Comment by xhdong-umd** [comment]
One possible case for this is that [multiple datasets with same individual](https://github.com/ctmm-initiative/ctmmweb/issues/58#issuecomment-387148948), which could cause some problem in name conflicts.

I think this feature can be very helpful but we must limit it to the typical user cases, otherwise there are too many possibilities and corner cases.
