### ISSUE TITLE
how many digits should we preserve?

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#57]
We have a lot of numbers in different places, with different meaning and units. 

I'm thinking maybe we should have a consistent format, like always keep 2 digits after decimal place (3 digits will be a little bit long in some places).

@jmcalabrese @chfleming @NoonanM What do you think?

**Comment by xhdong-umd** [comment]
In second thought, some places probably need more precision.

For example the overlap values are 0 - 1, the current 4 digits seemed to be fine. And 3 digits is good for the model summary table DOF etc.

**Comment by chfleming** [comment]
For numbers with confidence intervals, its the confidence interval that determine this. In general, I think CIs need at least 1-2 significant digits on their difference, like x = 1.2345 (1.2340 -- 1.2350) for example.

**Comment by xhdong-umd** [comment]
I assume I need to calculate this after getting calculation result from ctmm?

**Comment by chfleming** [comment]
Yes.

**Comment by xhdong-umd** [comment]
Now the model summary table will make sure the CI values have at leasts one significant digit on difference. Previously the last rows in table below were rounded to 2 digits and didn't show the difference.

<img width="344" alt="screen shot 2018-03-27 at 8 59 07 pm" src="https://user-images.githubusercontent.com/25039897/38002761-1f10df8c-3202-11e8-9df7-dc272a83e061.png">

**Comment by xhdong-umd** [comment]
Overlap table are also adjusted to reflect the significant digits needed for the difference.

<img width="773" alt="screen shot 2018-03-28 at 8 56 54 am" src="https://user-images.githubusercontent.com/25039897/38030252-137a2cfa-3266-11e8-8605-108dda071a3b.png">
