### ISSUE TITLE
Home range estimation

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#60]
When estimating home ranges, you can change the level of the contours in the plot, but the area estimates in the table aren't adjusted.

**Comment by xhdong-umd** [comment]
How do I incorporate that in the home range table?

I think `akde` don't have a parameter like `level.UD`, right? Does it need to be assigned somewhere in the summary of home range?

**Comment by NoonanM** [comment]
That's right, akde doesn't have a `level.UD` parameter, you would need to pass the contour level to `level.UD` in `summary()`

**Comment by xhdong-umd** [comment]
[This is based from ctmmweb vignette](https://ctmm-initiative.github.io/ctmmwebdoc/articles/package_usage.html#home-range), I tried to give a `level.UD` vector to summary on home range object but failed.

```r
...
hrange_list_sub2 <- akde(tele_list_sub2, CTMM = model_list_sub2)
lapply(hrange_list_sub2, summary)
```

```r
> summary(hrange_list_sub2[[1]])
$DOF
     area bandwidth 
 31.36118  45.88222 

$CI
                              low       ML    high
area (square kilometers) 240.4693 353.0512 486.909

> summary(hrange_list_sub2[[1]], level.UD = c(0.5, 0.95))
$DOF
     area bandwidth 
 31.36118  45.88222 

$CI
                              low       ML     high
area (square kilometers) 149.9753 220.1901 303.6742

Warning message:
In object$CDF <= level.UD :
  longer object length is not a multiple of shorter object length
```

**Comment by xhdong-umd** [comment]
So it seemed that it can take single level.UD value but not multiples, which is understandable, otherwise there need to be more columns correspond to different level.UD.

```r
> summary(hrange_list_sub2[[1]], level.UD = 0.5
+ )
$DOF
     area bandwidth 
 31.36118  45.88222 

$CI
                              low       ML     high
area (square kilometers) 59.48128 87.32899 120.4394

> summary(hrange_list_sub2[[1]], level.UD = 0.9)
$DOF
     area bandwidth 
 31.36118  45.88222 

$CI
                              low       ML     high
area (square kilometers) 192.0662 281.9871 388.9012
```

**Comment by xhdong-umd** [comment]
Unless we plan to add more rows in the table like

low at 0.5 CI
high at 0.5 CI
low at 0.9 CI
high at 0.9 CI
...

We can only take single input into account.

**Comment by NoonanM** [comment]
I think single inputs would be a useful start, but longer term it might be good to have this page handle multiple inputs. People regularly calculate 95% and 50% home range areas.

The way the table is currently set up, it looks like there might be space for more columns. Maybe one option would be to call the 'area' column '95% area' by default, and if the user adds multiple inputs for `level.UD`, new columns get added in with appropriate titles? e.g., `c(0.95, 0.50)` would produce two columns one for the 95% area, a second for the 50% area.

**Comment by xhdong-umd** [comment]
It's doable however I'll avoid to put more columns. More columns make table too wide and difficult to read. 

We can use the current structure to add more rows like this (the names probably are not the best ones, I'll leave them for you to choose the better descriptions)

| estimate | area |
|----------|------|
| CI -0.50 | ..   |
| CI -0.95 | ...  |
| ML       | ...  |
| CI 0.95  | ...  |
| CI 0.50  | ...  |

**Comment by NoonanM** [comment]
Ok, if you think more columns will make it look cluttered, that's fine. ML will need .95 and .50 as well.

**Comment by xhdong-umd** [comment]
Looking at these two tables, is there any wrong that home range `area` is different from the `area` in model summary table?
<img width="714" alt="screen shot 2018-03-27 at 2 49 37 pm" src="https://user-images.githubusercontent.com/25039897/37988218-57993fb8-31ce-11e8-8012-63b0fcfeac35.png">

<img width="698" alt="screen shot 2018-03-27 at 2 51 04 pm" src="https://user-images.githubusercontent.com/25039897/37988225-5e00996e-31ce-11e8-8608-e746ee717689.png">

I'm also wondering if there is better method to represent the information. If user input 3 `level.UD` values, that will be 9 rows/columns for each animal. 9 columns make the table too wide, 9 rows per animal are also not optimal when the majority columns are sharing same information.

Maybe we only use the default value in the sortable table, and just print a plain text table with more values in columns?

**Comment by xhdong-umd** [comment]
I agree. It may be a better design to keep the default table with default CI in first tab, and put all customized CI levels in 2nd tab. 

I can also try a plain table instead the DT table, just like when you print a data.frame in R. A plain table should take less spaces. We can try to put CI levels in columns and use a different design from the main table. Do we still need the `DOF  area`, `DOF bandwidth` column in 2nd table?

**Comment by xhdong-umd** [comment]
Or maybe we should just add a legend to each plot like this?

0.5 : (100, 150, 200) km2
0.95: ( 120, 160, 180) km2

**Comment by NoonanM** [comment]
`DOF area`, and `DOF bandwidth` will be the same, so it would be duplicate information. I don't see the need for it but maybe @chfleming or @jmcalabrese think differently?

**Comment by NoonanM** [comment]
Both the legend and table seem like good options. I don't have a preference.

**Comment by NoonanM** [comment]
I've been thinking about this, and I think a table might be better. Users will likely want to report those numbers and a table will save them from having to re-type the numbers, whereas with the legend, they won't be able to copy the numbers from the image.

**Comment by xhdong-umd** [comment]
Yes I thought about that. 

We actually can print the table in the console log, and it will be saved in the work report. User can copy the table from the work report or console, and there will be all the context about the data.

**Comment by xhdong-umd** [comment]
If the common use case will not use too many level values, using existing table with additional rows might be OK. The `level.UD` name can be changed if you found a better name.

<img width="690" alt="screen shot 2018-03-29 at 2 41 27 pm" src="https://user-images.githubusercontent.com/25039897/38107266-6d05c8c0-335f-11e8-95ac-96d84b9b4b14.png">

**Comment by xhdong-umd** [comment]
Additional columns have some problems:
- The table could be quite wide, and scrolling horizontally is usually harder than scrolling vertically.
- The table will not be "tidy". I don't really use the tidy names but put every single observation in row do make operations on table much easier. 
- You also cannot sort by the CI values when they are in column names. Right now you can sort them easily.

As long as the number of CI values <= 3, I think the current table is acceptable and we don't need to use other approach like additional table or legend in plots.

I'll change the column name to `quantile` and make the value * 100 to be consistent with user input.

**Comment by NoonanM** [comment]
Sounds good.

**Comment by xhdong-umd** [comment]
Done.
