### ISSUE TITLE
Maximum File Size

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#62]
A user is having issues with loading in saved data. After saving, and trying to load back in, the app says the file size limit has been exceeded.

**Comment by xhdong-umd** [comment]
The shiny upload file size has a limit, previously I set it to about 200M. Now with the saved data we may need bigger limit. I'll increase it to 1G.

**Comment by NoonanM** [comment]
Yeah the user in question has 36 animals, so that's within the range many studies might have. The larger file size limit will be useful.

**Comment by xhdong-umd** [comment]
There is nothing to prevent we set it to a very big number, but uploading large file through browser will be quite slow, and plots with lots of points can be slow too.

**Comment by xhdong-umd** [comment]
Changed to 2G and updated the repo.
