### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#64]
I tried a fresh install of the app on both mac and windows using:

```
if (!require("remotes")) install.packages("remotes")
remotes::install_github("ctmm-initiative/ctmmweb")
 
library(ctmmweb)
 
app()
```

and it failed with the following error:

`Error in server(...) : object 'DEBUG_BUTTON' not found`

**Comment by dracodoc** [comment]
Thanks for the report (you don't need to test in 2 platforms, one is enough), it's some left over not removed. I was working on several issues in the same time so didn't get time to test with clean state. Next time I should keep masrer branch stable and only update my development branch.

**Comment by xhdong-umd** [comment]
The account above is my personal account, I used my cell phone which was logged in with that account.

I just fixed it and updated the repo.
