### ISSUE TITLE
Add other ctmm package dataset to app; improve occurrence calculation

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#67]
I'm trying to load other ctmm package internal data to app, however all other 3 data set cannot work because they are anonymized data (just x, y, t) without a timestamp column, and the location data don't have coordinates so map page will not work either. 

All the app code have the assumption that the data meet movebank format requirement and have a valid timestamp. Without timestamp the time subsetting, time axis in plot also doesn't work.

@chfleming @NoonanM 
Is there any way we can fix this? Otherwise we may have to skip this feature.

**Comment by chfleming** [comment]
The coati dataset that is about to go in will be Movebank format. So it will just be the buffalo and coati. I'll update you when that goes in.

**Comment by xhdong-umd** [comment]
OK. I implemented the feature as this:

<img width="655" alt="screen shot 2018-07-26 at 4 11 04 pm" src="https://user-images.githubusercontent.com/25039897/43285962-9b1008d8-90ee-11e8-89d2-0d8a742a21f9.png">

- Select a row in the data set table, click "load" button will load that data set.
- The checkbox of taking sample and the sample size text input control the sample feature. It's on by default now so it's easier for my development. It can be turned off by default when released.
- I moved the movebank login control to next movebank box.

@jmcalabrese @NoonanM Should we move all movebank stuff into a separate movebank page?

**Comment by xhdong-umd** [comment]
@chfleming In testing with `coati` data set I found there was some warning in plot, and the occurrence calculation is quite slow for 2nd animal which only have 79 rows. 

```r
library(ctmm)
library(ctmmweb)
data(coati)
data_sample <- coati
model_try_res <- par_try_models(data_sample)
#  user  system elapsed 
# 3.332   0.678  43.436 
model_list <- flatten_models(model_try_res)
# 3 models in list, 1 and 3 are best model for each animal
occur_list <- par_occur(data_sample,  model_list[c(1,3)])
# it took a long time. turned out to be 2nd animal
system.time(ctmm::occurrence(data_sample[[2]], model_list[[3]]))

plot(occur_list[[1]])
plot(occur_list[[2]], level.UD = c(0.50, 0.95))
# Warning message:
# In x$CDF <= P :
#   longer object length is not a multiple of shorter object length
```

**Comment by chfleming** [comment]
I could have accidentally fixed something, but I didn't get that warning when running occurrence() on the second coati. Run time was long with default arguments, probably because the data contains large gaps. Users can set `cor.min` smaller or `dt.max` to some multiple of the sampling rate to prevent this kind of slowdown... which can sometimes cause OOM.

Unrelated to this, I simplified the `overlap()` arguments: https://groups.google.com/forum/#!topic/ctmm-user/mDskFopnU5M

**Comment by xhdong-umd** [comment]
I tested the above code again with the latest ctmm version, and I'm still seeing the warning in the plot (not in occurrence(), but in the plot of occurrence with two level.UD value)

```r
> system.time(occur_list <- par_occur(data_sample,  model_list))
running parallel with mclapply in cluster of 2 
   user  system elapsed 
156.759  52.759 934.060 

> plot(occur_list[[2]], level.UD = c(0.50, 0.95))
Warning message:
In x$CDF <= P :
  longer object length is not a multiple of shorter object length
```

I'm thinking maybe we should not expose coati data in app if the default action in app will take this much time (15 mins).

**Comment by chfleming** [comment]
I figured out the warning---it was from extent().

I think for the occurrence() functionality, we just need to open up the `cor.min` and `dt.max` options---possibly calculating one from the other on the fly. This is a common issue with occurrence distributions and not specific to the coati.

**Comment by xhdong-umd** [comment]
For the `cor.min` and `dt.max` options, does it need user's choice or it can be done automatically?

**Comment by chfleming** [comment]
Unfortunately, its not obvious what the best choice would be, as it has to do with how fast the Gaussian model becomes a misspecification of the true model.

The user only has to specify one of the two arguments and they are related via
`dt.max <- -log(cor.min)*CTMM$tau[1]`
and
`cor.min <- exp(-dt.max/CTMM$tau[1])`
so it would be nice if when the user specified one argument, the other was updated.

`dt.max` is the maximum gap size to interpolate (with units of time)
`cor.min` is the minimum position autocorrelation to retain over interpolated gaps (unitless).

**Comment by xhdong-umd** [comment]
So there are several steps of choices involved, how many of them can be done automatically?

1. whether to enable these arguments vs default options, according to data
2. if to enable arguments,  can each argument value be calculated automatically?
3. to chose which one and let it determine another one, this need to be user's choice

**Comment by chfleming** [comment]
Actually, thinking about it further, the conversion between the arguments is different per individual, so if one is used, then the other input box needs to be left empty.

The default argument is `cor.min=0.5`.

**Comment by chfleming** [comment]
That default argument is totally arbitrary, though.

**Comment by chfleming** [comment]
I'm not keen on that as similar issues will arise in the user data. I'd rather address the issue as best as possible.

**Comment by chfleming** [comment]
The default arguments are much more sensible now and shouldn't slow down on datasets like this any more.
