### ISSUE TITLE
Time subsetting

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#68]
I've noticed an issue where time subsetting doesn't seem to work. The data load in correctly, and the bins look good, but when I drag to select them, nothing happens.

<img width="1904" alt="screen shot 2018-08-09 at 5 45 20 pm" src="https://user-images.githubusercontent.com/26824892/43927624-29f160c0-9bfc-11e8-9796-8174c46995b6.png">

**Comment by NoonanM** [comment]
This is not specific to a single dataset. I also can't subset with either the buffalo, or the coati data.

**Comment by dracodoc** [comment]
I will look at it. Probably caused by so many changes to code recently, and I didn't test every page in my usual testing.

**Comment by NoonanM** [comment]
It now seams to be running properly. One issue I've noticed though is that when you click and drag on the scatter plot, you can zoom in on a selection. After you do that though, there's no way to zoom back out.

**Comment by xhdong-umd** [comment]
To quit zoom you need to double click on plot. This is not obvious if you don't know it before. I explained it in the visualization page help, as the zoom in/out works in most location plots.

**Comment by NoonanM** [comment]
Yup, that works, ok thanks. Sorry... should have checked the help file...
