### ISSUE TITLE
Exporting Data

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#71]
I've noticed a strange behavior where, if you're on the Visualization page, and you select a subset of individuals, and you then click `Export Current', it only exports one individual. If you click it again, it exports 2, again and it exports 3, and so on until all of the selection has been exported.

**Comment by xhdong-umd** [comment]
Strange, it's working normal for me. I selected two individuals, then `export current` will save a csv that holding that two individuals.

**Comment by xhdong-umd** [comment]
I modified app to log the current data when exporting. Can you try latest version to see what's the output in console when you `export current`?

**Comment by NoonanM** [comment]
I think it's related to my computer, not the app. It's been running slowly all day.
