### ISSUE TITLE
Keep Best Only

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#73]
"Keep Best Only" is too confusing to users. They think they need to click this button to only use the good models... and otherwise they will get some bad models in further analysis.

I suggest renaming this to something like "Remove duplicate models".

**Comment by xhdong-umd** [comment]
Are the models to be removed really duplicates? How about "Remove suboptimals"? That actually was my initial wording.

**Comment by chfleming** [comment]
They are duplicates of the model type, just not necessarily of the optimization. "Remove suboptimals" might also make people think they *need* to click that button.

"Remove worst refits" ?

Can the button not be present/operational unless the models are actually refit?

**Comment by xhdong-umd** [comment]
That button can be used to clean up the models even without refit, it can be done but unless you don't want it without refit.

"Clean up results"?

**Comment by chfleming** [comment]
What does it do if nothing was refit?

Clean up sounds good, I think.

**Comment by xhdong-umd** [comment]
Remove all models except the best fit for each individual.

**Comment by xhdong-umd** [comment]
I changed it to "Clean Up".
