### ISSUE TITLE
installer for local installation

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#76]
Although we have instructions in github readme, some users may not read/realize or know how to install the package locally.

I'll edit the readme to make it as short as possible, make the local install option more obvious.

I'll also explore whether we can create a installer package/installer.

- platform
   The main focus should be windows. Mac OS and linux should also be considered if possible.
- approaches
   - installer package. There are many disadvantages to a full installer. We need to deal with platform details (windows versions), maintain the installer for changes in R.
   - installer script. User download a script then run from machine. This is easy and transparent (knowledgable user can read the script and know it's safe). We can pack the script to be easily clickable. This can also work for platform other than windows.
      
There may be also some existing tool/package for this.

**Comment by xhdong-umd** [comment]
I edited [the readme](https://github.com/ctmm-initiative/ctmmweb/tree/package) to make it simpler. 

Hope user will read it and get the idea. It's not in master branch for now because I still need to work on best option on release and installer.

**Comment by NoonanM** [comment]
Another piece that might be useful is an "updater". 

Assuming that everything has already been installed, for mac it could be a simple apple script packaged as a downloadable app e.g.,

tell application "R"
	activate
	cmd "devtools::install_github("ctmm-initiative/ctmmweb")"
end tell

**Comment by xhdong-umd** [comment]
Yes, actually everything can be done from script (including download a installer and run it), and it'll be easy to maintain and deploy. However I'm afraid windows user might not be familiar with download a script and run it. They are more comfortable with installers. 

For windows my current plan is:

- It will be a innosetup installer, about 1M size. Once downloaded and started, it will first download R windows installer and run it. With R installed, the installer will continue to copy some .bat files and create shortcut in start menu and desktop. The whole thing can be uninstalled.
  If user have R already, they can skip the R installer part.
- There will be shortcut for just updating the app, and for running the app. Also shortcut to install the release version and one to install development version. These shortcut are just .bat files running RScript. 
   I'm trying to find R install path in windows with .bat now. R windows installer doesn't put the path into PATH environment so I have to look up the registry.

I'll first focus on windows, then look at Mac.

**Comment by NoonanM** [comment]
Ok, great. Sounds like you've thought of all the pieces then.

Also, yes, windows is probably the place to start. My guess is that it has the largest base of users unfamiliar with command line.

**Comment by chfleming** [comment]
I also know with Windows, installing a new version of R does not automatically uninstall old versions of R. We will need to automate that as well.

I thought the windows R installer had the option of modifying the PATH, but maybe it isn't default?

**Comment by xhdong-umd** [comment]
I'll try to uninstall old version.

Windows installer will not touch PATH(it's tricky to work with path too, with permission limits sometimes user can only modify user environment but not system environment), only add path to registry by default. If user deselected that option, we will have no way to know about the path. I'm just hoping most users will not change that option.

https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Rcmd-is-not-found-in-my-PATH_0021

>The R installer does not put Rcmd.exe (nor any other R executable) on your PATH. 

https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-use-the-Registry_003f

>When you run the R installer, there are options (under ‘Select Additional Tasks’) to ‘Save version number in registry’ and (for Administrator installs) ‘Associate R with .RData files’.

**Comment by xhdong-umd** [comment]
Do you think it's a good idea to have a button inside app to update itself?

The idea case is to update self and launch new version again, but that requires too much background handling. For now I can make it to quit the app, run installation code automatically (I cannot make it run app automatically afterwards because background process will cause problems). It will be same with clicking a `update app` shortcut with our installer, just run it from inside the app.

**Comment by chfleming** [comment]
I think that's a good idea. Also, if the button/option flagged in some way when an update was available.

**Comment by xhdong-umd** [comment]
We can let the app check new releases in each run, this is easy but could be too slow(and if there is no internet it has to be timeout so wait for some time). 

Ideally it should only check every month or so, then I need to save last checked time in disk somewhere. I'll check if this can be done.

**Comment by xhdong-umd** [comment]
Making the installer to detect R path is really not easy. First I tried to use batch file in windows, then I realized the better option is for the installer to detect path. Innosetup support Pascal script which should have the capability, but I need to learn the syntax and usage of this language to
1. detect path in registry
2. pop up a dialog ask to user to manually input if no path is detected
3. create shortcuts with path

Right now I'm having problems with syntax...


@jmcalabrese @chfleming @NoonanM 
I'm not sure if this can be done before course, maybe I should test with ctmm (I have done some basic tests which seemed OK), and add the self update feature first, then make a release version. After that I'll continue working on the installer.

I have experimented with the alternative package installation solution which is hosting the package as a repo, so there is no need to use devtools.

**Comment by jmcalabrese** [comment]
A stable release for the course is more important than the installer, so do the release first, and work on the installer later.

**Comment by xhdong-umd** [comment]
The self update method I tried can only work with `install.package` call (the official releases can be hosted in customized repo and can be installed with `install.package`) but not with `devtools::install_github`(which is used to install latest development version). 

It's tricky because the app need to quit itself, schedule a update. `devtools` seemed interfere with the process more and prevented a clean exit (it worked in a simple test app but not in the actual webapp).

I'm wondering whether this is still useful if it can only install release version.

**Comment by xhdong-umd** [comment]
I updated the project readme to make it very simple and clear. I also rewrote the installation page, hope its easy to follow for most users.

<img width="963" alt="screen shot 2019-02-07 at 4 27 51 pm" src="https://user-images.githubusercontent.com/25039897/52444137-88ae7700-2af5-11e9-963e-946dd4fc4c4b.png">

Package version updated to 0.2.3 to match ctmm 0.5.3. I intend to always match the last digit for the tested CRAN version. I also updated NEWS, hosted app. I will make the release tomorrow when there is nothing to change.

**Comment by xhdong-umd** [comment]
After spending one whole day on the installer issue, I finally made one. 

@jmcalabrese @chfleming @NoonanM You can download the ctmmwebsetup.exe from [this page](https://github.com/ctmm-initiative/ctmmweb/releases/tag/v0.2.5)

The installer will download R installer and run it first, then detect R path, modify Path variable, install ctmmweb package (it may need install quite some in first time), and place a shortcut in start menu. User can start the app from start menu later. There is also batch files in installed folder for updating github version. The program can be uninstalled properly.

There are some limits:
- User better install R to some folder they have full access, but the default folder in program files may cause problem later(they can install R to that folder but cannot install packages later). See [details here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-run-under-Windows-Vista_003f).
- User better do not change the default option of "save R version info to registry" in R installation, otherwise we cannot find R installation path. Hopefully most user will not change it.

**Comment by NoonanM** [comment]
I can't test it on my mac, but sounds good.

**Comment by xhdong-umd** [comment]
I finally made it work with the better design. The installer is updated.

- Download and install R is optional, and it will not download if not selected (seemed simple but not easy with limited documentation and all the tricky things)
- Adding path is not optional since it's a required condition to run the app properly.
- User still need to not change the default `save R version into registry` option. There is nothing we can do in our end for this.

Interestingly, I found the app start and run much slower in my old PC. It was not too slow running other programs. Not sure if it's R or Shiny's limitations.

**Comment by xhdong-umd** [comment]
I updated the installer:
- R updated to 3.5.3
- The installer will add these to a folder in start menu: 
  - link to app
  - update script
  - project website url

**Comment by xhdong-umd** [comment]
Next I will add some check on the app to check updates every 1-2 months.

**Comment by xhdong-umd** [comment]
I added code to check new release every 60 days. 
- The check will time out after 3 seconds if there is a network issue. 
- The app will only run the check every 60 days. 
- If there is error in fetching update information (it rely on github API to check latest release package), error information will be displayed
- If new version is found, app will remind user to update the app with this message:

`New version found, please update the package. Windows user can run the update app link from start menu.`

**Comment by NoonanM** [comment]
I was working with a user who installed the package using the installer. It ran through to completion, they used all of the default settings, but the desktop icon doesn't do anything. A command prompt window opens, but then closes before running the lines to open the app.

I'm not sure how to better explain the issue.

**Comment by xhdong-umd** [comment]
We need to first find out the exact error message. The icon just point to a .bat file in installed folder, so just start windows command line prompt in that folder and run the bat file in command line, that should make it possible to see the error.

My guess is some path or registry problems not working as expected.

**Comment by NoonanM** [comment]
After restarting their computer, the app icon no functions properly. No idea why it was not working previously...
