### ISSUE TITLE
Fine tuning and refitting variogram window after model selection

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#81]
For the popup window where you can fine tune the fit parameters, zoom into the variogram and refit the model, at least on @markyxe 's data, the window works right after you fit the models, but then when you leave that page and go back (or load previous results in a new session) the window no longer comes up.

**Comment by xhdong-umd** [comment]
I didn't find this problem with other test data set. I don't have @markyxe 's data so I cannot reproduce this or look into another problem reported about tao without unit.

I found [there was an error calling `ctmm.guess` with another data set](https://github.com/ctmm-initiative/ctmmweb/issues/79#issuecomment-463730901), how should we deal with that?

**Comment by xhdong-umd** [comment]
I think this is one of the confusing aspect of the selectinput. After you come back, the input is showing last selection value, but if you just click on it, it didn't bring any change to the interface thus will not trigger any update to app. You need to use backspace to delete the last value then select again. In this way it will work. Also this apply to the page before model selection too.

I could make the pop up window clear the input after applying the changes so there will not be this problem, however it's hard to catch the cancel button behavior and add similar code, so this approach is not perfect.
