### ISSUE TITLE
Plot tweaks

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#85]
I think some of the ggplot2 plots generated by the webapp need some refinement to be "publication quality". I'll give two examples here:

1) In the overview scatter plot, the "id" label on the legend should be removed (I circled it in the attached), and the axis labels, legend entries, and tick labels should be larger, with the axis labels being noticeably larger than the other text elements.

![Overview_example](https://user-images.githubusercontent.com/26653992/57343715-6a671000-7112-11e9-91b3-f81eddbf72f8.png)

2) In the overlap estimate + CI plot, there is a useless legend on the right hand side of the plot that should be removed. All of the text in the figure should be larger (again with axis labels larger than other text elements), the blue points for the point estimates should be larger, and the red bars denoting the CIs should be a bit thicker.

![Overlap_example](https://user-images.githubusercontent.com/26653992/57343841-f842fb00-7112-11e9-9c9b-2804c964e43c.png)

**Comment by xhdong-umd** [comment]
Hi @jmcalabrese , I'll tweak the plots as you requested.

For the #2 CI plot, the legend was for the case when user selected some rows in the table above, and the selected values will be highlighted with a different color. Without any row being selected the legend don't provide any information.

There are two approaches:
1. turn off this legend completely
2. turn it off when nothing was selected, but turn it on when user do selected some rows (also fine tune the legend details a little bit).

Which one do you prefer?

**Comment by jmcalabrese** [comment]
@xhdong-umd I think for the overlap plot, option 2 would be best.

**Comment by xhdong-umd** [comment]
Here is a modified overview plot. For this plot, `x` `y` itself is small so even a bigger font size don't appear too much. However other plot with same axis label size will look too big. I'll adjust them as well.

<img width="635" alt="Screen Shot 2019-05-09 at 5 38 29 PM" src="https://user-images.githubusercontent.com/25039897/57488532-58f04600-7281-11e9-8f57-4ff11cd4f2fb.png">

Overlap plot is like this (I still need to adjust the legend, and expand the canvas a little bit to accommodate the text)

<img width="909" alt="Screen Shot 2019-05-09 at 6 05 51 PM" src="https://user-images.githubusercontent.com/25039897/57489806-33653b80-7285-11e9-953f-7c9d8c09338c.png">

**Comment by xhdong-umd** [comment]
@jmcalabrese, I updated master branch and you can have a test. The axis label seemed to be a little big for me though.
