### ISSUE TITLE
No units or CIs on OUf tau parameter estimate

### ISSUE THREAD

**Issue by chfleming** [ctmm-initiative/ctmmweb#86]
In the model-fit summary table, there are no units or confidence intervals reported on the new OUf tau parameter estimates.

Specifically for the OUf model, it would be even more ideal to copy its tau estimate to both tau_position and tau_velocity, as they are constrained to be identical for that model.

**Comment by xhdong-umd** [comment]
Sorry I didn't get time to fix this earlier. The question reported by @Ferazevedo is actually this issue. I have added the unit and CI for tau.

However I'd like to keep the model summary result consistent with what ctmm got. If I copy the tau estimate to tau_position/tau_velocity but ctmm is showing them as NA, that might cause some confusion.

**Comment by xhdong-umd** [comment]
@chfleming , so you mean tau is only available for OUf, and I don't need to create tau, just put its value into tao_position, tau_velocity. Other models will not have tau value.

The model summary code is quite complex and I forgot many details. Now I got it.

**Comment by chfleming** [comment]
OUf has a `tau`, which is equal to `tau[position]` and `tau[velocity]`. This is the only model with just `tau`.

OUO has something like `tau[decay]` and `tau[oscillation]`. I can look it up if you need. It wouldn't be terrible to treat `tau[decay]` the same way, but `tau[oscillation]` (or `tau[period]`?) is pretty different.

**Comment by xhdong-umd** [comment]
I copied tau value of OUf to tau position and tau velocity. Though they are using different units because each column are formatted with best unit for whole column.

![2020-09-03_130124](https://user-images.githubusercontent.com/25039897/92145139-c95f9680-ede5-11ea-943e-eeca434730e1.png)

Do you want to copy tau[decay] to tau position, tau velocity for OUO too?

**Comment by chfleming** [comment]
That sounds good.

**Comment by xhdong-umd** [comment]
tau are always time, right? I need to format them and take proper unit.

**Comment by chfleming** [comment]
Yes.

**Comment by xhdong-umd** [comment]
Done.
