### ISSUE TITLE
Save progress bug when launching from Windows desktop icon

### ISSUE THREAD

**Issue by jmcalabrese** [ctmm-initiative/ctmmweb#92]
@xhdong-umd 3 people from the course have encountered a bug where they can't save their progress in the webapp. All of them are on Windows, used the windows wizard installer, and launched the webapp from the launch icon created by the installer. When they restart the webapp by launching it directly from an R console, save progress works fine, so the problem seems to be related to launching the webapp from the desktop icon.

**Comment by xhdong-umd** [comment]
The launch shortcut is a link to windows .bat file, which in turn call a line of starting app with RScript. The difference should be more about platform specific, like if same browser is used, or if there is multiple R version/path issues etc.

Is there any error message available? Did the app just hang?

**Comment by xhdong-umd** [comment]
I tested again with current version and didn't see any problem. I will close this unless there are new report with more details.
