### ISSUE TITLE
Data saving issue

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#93]
When saving progress, the exported csv file does not keep all of the columns ctmm needs to calibrate error. This means that is a user does some work, saves their progress, comes back at a later time and tries to calibrate their errors again, they get an error.

The exported csv should keep all of the columns in the telemetry object.

**Comment by xhdong-umd** [comment]
The csv only have the data frame part of the telemetry object. I believe the error information is in some slots, not dataframe.

All the objects actually should be saved in. rds when saving progress. You can check the help page for saving progress, though I need to double check about error part.
